package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdColor generated by hbm2java
 */
public class AdColor  implements java.io.Serializable {


     private long adColorId;
     private AdImage adImage;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private char isdefault;
     private char colortype;
     private long red;
     private long green;
     private long blue;
     private long alpha;
     private BigDecimal imagealpha;
     private Long red1;
     private Long green1;
     private Long blue1;
     private Long alpha1;
     private Long linewidth;
     private Long linedistance;
     private Long startpoint;
     private Long repeatdistance;
     private Set adWindows = new HashSet(0);
     private Set adWorkbenches = new HashSet(0);

    public AdColor() {
    }

	
    public AdColor(long adColorId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isdefault, char colortype, long red, long green, long blue, long alpha, BigDecimal imagealpha) {
        this.adColorId = adColorId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isdefault = isdefault;
        this.colortype = colortype;
        this.red = red;
        this.green = green;
        this.blue = blue;
        this.alpha = alpha;
        this.imagealpha = imagealpha;
    }
    public AdColor(long adColorId, AdImage adImage, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isdefault, char colortype, long red, long green, long blue, long alpha, BigDecimal imagealpha, Long red1, Long green1, Long blue1, Long alpha1, Long linewidth, Long linedistance, Long startpoint, Long repeatdistance, Set adWindows, Set adWorkbenches) {
       this.adColorId = adColorId;
       this.adImage = adImage;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.isdefault = isdefault;
       this.colortype = colortype;
       this.red = red;
       this.green = green;
       this.blue = blue;
       this.alpha = alpha;
       this.imagealpha = imagealpha;
       this.red1 = red1;
       this.green1 = green1;
       this.blue1 = blue1;
       this.alpha1 = alpha1;
       this.linewidth = linewidth;
       this.linedistance = linedistance;
       this.startpoint = startpoint;
       this.repeatdistance = repeatdistance;
       this.adWindows = adWindows;
       this.adWorkbenches = adWorkbenches;
    }
   
    public long getAdColorId() {
        return this.adColorId;
    }
    
    public void setAdColorId(long adColorId) {
        this.adColorId = adColorId;
    }
    public AdImage getAdImage() {
        return this.adImage;
    }
    
    public void setAdImage(AdImage adImage) {
        this.adImage = adImage;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public char getColortype() {
        return this.colortype;
    }
    
    public void setColortype(char colortype) {
        this.colortype = colortype;
    }
    public long getRed() {
        return this.red;
    }
    
    public void setRed(long red) {
        this.red = red;
    }
    public long getGreen() {
        return this.green;
    }
    
    public void setGreen(long green) {
        this.green = green;
    }
    public long getBlue() {
        return this.blue;
    }
    
    public void setBlue(long blue) {
        this.blue = blue;
    }
    public long getAlpha() {
        return this.alpha;
    }
    
    public void setAlpha(long alpha) {
        this.alpha = alpha;
    }
    public BigDecimal getImagealpha() {
        return this.imagealpha;
    }
    
    public void setImagealpha(BigDecimal imagealpha) {
        this.imagealpha = imagealpha;
    }
    public Long getRed1() {
        return this.red1;
    }
    
    public void setRed1(Long red1) {
        this.red1 = red1;
    }
    public Long getGreen1() {
        return this.green1;
    }
    
    public void setGreen1(Long green1) {
        this.green1 = green1;
    }
    public Long getBlue1() {
        return this.blue1;
    }
    
    public void setBlue1(Long blue1) {
        this.blue1 = blue1;
    }
    public Long getAlpha1() {
        return this.alpha1;
    }
    
    public void setAlpha1(Long alpha1) {
        this.alpha1 = alpha1;
    }
    public Long getLinewidth() {
        return this.linewidth;
    }
    
    public void setLinewidth(Long linewidth) {
        this.linewidth = linewidth;
    }
    public Long getLinedistance() {
        return this.linedistance;
    }
    
    public void setLinedistance(Long linedistance) {
        this.linedistance = linedistance;
    }
    public Long getStartpoint() {
        return this.startpoint;
    }
    
    public void setStartpoint(Long startpoint) {
        this.startpoint = startpoint;
    }
    public Long getRepeatdistance() {
        return this.repeatdistance;
    }
    
    public void setRepeatdistance(Long repeatdistance) {
        this.repeatdistance = repeatdistance;
    }
    public Set getAdWindows() {
        return this.adWindows;
    }
    
    public void setAdWindows(Set adWindows) {
        this.adWindows = adWindows;
    }
    public Set getAdWorkbenches() {
        return this.adWorkbenches;
    }
    
    public void setAdWorkbenches(Set adWorkbenches) {
        this.adWorkbenches = adWorkbenches;
    }




}


