package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdColumn generated by hbm2java
 */
public class AdColumn  implements java.io.Serializable {


     private long adColumnId;
     private BigDecimal version;
     private AdTable adTable;
     private AdClient adClient;
     private AdReference adReferenceByAdReferenceId;
     private AdProcess adProcess;
     private AdValRule adValRule;
     private AdOrg adOrg;
     private AdElement adElement;
     private AdEntitytype adEntitytype;
     private AdReference adReferenceByAdReferenceValueId;
     private char isactive;
     private Date created;
     private Date updated;
     private long createdby;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private String columnname;
     private Long fieldlength;
     private String defaultvalue;
     private char iskey;
     private char isparent;
     private char ismandatory;
     private char isupdateable;
     private String readonlylogic;
     private char isidentifier;
     private Long seqno;
     private char istranslated;
     private char isencrypted;
     private String callout;
     private String vformat;
     private String valuemin;
     private String valuemax;
     private char isselectioncolumn;
     private Character issyncdatabase;
     private char isalwaysupdateable;
     private String columnsql;
     private String mandatorylogic;
     private String infofactoryclass;
     private char isautocomplete;
     private Character isallowlogging;
     private String formatpattern;
     private Set adWfNodes = new HashSet(0);
     private Set adWorkbenches = new HashSet(0);

    public AdColumn() {
    }

	
    public AdColumn(long adColumnId, BigDecimal version, AdTable adTable, AdClient adClient, AdReference adReferenceByAdReferenceId, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, Date updated, long createdby, long updatedby, String name, String columnname, char iskey, char isparent, char ismandatory, char isupdateable, char isidentifier, char istranslated, char isencrypted, char isselectioncolumn, char isalwaysupdateable, char isautocomplete) {
        this.adColumnId = adColumnId;
        this.version = version;
        this.adTable = adTable;
        this.adClient = adClient;
        this.adReferenceByAdReferenceId = adReferenceByAdReferenceId;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.updated = updated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.name = name;
        this.columnname = columnname;
        this.iskey = iskey;
        this.isparent = isparent;
        this.ismandatory = ismandatory;
        this.isupdateable = isupdateable;
        this.isidentifier = isidentifier;
        this.istranslated = istranslated;
        this.isencrypted = isencrypted;
        this.isselectioncolumn = isselectioncolumn;
        this.isalwaysupdateable = isalwaysupdateable;
        this.isautocomplete = isautocomplete;
    }
    public AdColumn(long adColumnId, BigDecimal version, AdTable adTable, AdClient adClient, AdReference adReferenceByAdReferenceId, AdProcess adProcess, AdValRule adValRule, AdOrg adOrg, AdElement adElement, AdEntitytype adEntitytype, AdReference adReferenceByAdReferenceValueId, char isactive, Date created, Date updated, long createdby, long updatedby, String name, String description, String help, String columnname, Long fieldlength, String defaultvalue, char iskey, char isparent, char ismandatory, char isupdateable, String readonlylogic, char isidentifier, Long seqno, char istranslated, char isencrypted, String callout, String vformat, String valuemin, String valuemax, char isselectioncolumn, Character issyncdatabase, char isalwaysupdateable, String columnsql, String mandatorylogic, String infofactoryclass, char isautocomplete, Character isallowlogging, String formatpattern, Set adWfNodes, Set adWorkbenches) {
       this.adColumnId = adColumnId;
       this.version = version;
       this.adTable = adTable;
       this.adClient = adClient;
       this.adReferenceByAdReferenceId = adReferenceByAdReferenceId;
       this.adProcess = adProcess;
       this.adValRule = adValRule;
       this.adOrg = adOrg;
       this.adElement = adElement;
       this.adEntitytype = adEntitytype;
       this.adReferenceByAdReferenceValueId = adReferenceByAdReferenceValueId;
       this.isactive = isactive;
       this.created = created;
       this.updated = updated;
       this.createdby = createdby;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.columnname = columnname;
       this.fieldlength = fieldlength;
       this.defaultvalue = defaultvalue;
       this.iskey = iskey;
       this.isparent = isparent;
       this.ismandatory = ismandatory;
       this.isupdateable = isupdateable;
       this.readonlylogic = readonlylogic;
       this.isidentifier = isidentifier;
       this.seqno = seqno;
       this.istranslated = istranslated;
       this.isencrypted = isencrypted;
       this.callout = callout;
       this.vformat = vformat;
       this.valuemin = valuemin;
       this.valuemax = valuemax;
       this.isselectioncolumn = isselectioncolumn;
       this.issyncdatabase = issyncdatabase;
       this.isalwaysupdateable = isalwaysupdateable;
       this.columnsql = columnsql;
       this.mandatorylogic = mandatorylogic;
       this.infofactoryclass = infofactoryclass;
       this.isautocomplete = isautocomplete;
       this.isallowlogging = isallowlogging;
       this.formatpattern = formatpattern;
       this.adWfNodes = adWfNodes;
       this.adWorkbenches = adWorkbenches;
    }
   
    public long getAdColumnId() {
        return this.adColumnId;
    }
    
    public void setAdColumnId(long adColumnId) {
        this.adColumnId = adColumnId;
    }
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
    public AdTable getAdTable() {
        return this.adTable;
    }
    
    public void setAdTable(AdTable adTable) {
        this.adTable = adTable;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdReference getAdReferenceByAdReferenceId() {
        return this.adReferenceByAdReferenceId;
    }
    
    public void setAdReferenceByAdReferenceId(AdReference adReferenceByAdReferenceId) {
        this.adReferenceByAdReferenceId = adReferenceByAdReferenceId;
    }
    public AdProcess getAdProcess() {
        return this.adProcess;
    }
    
    public void setAdProcess(AdProcess adProcess) {
        this.adProcess = adProcess;
    }
    public AdValRule getAdValRule() {
        return this.adValRule;
    }
    
    public void setAdValRule(AdValRule adValRule) {
        this.adValRule = adValRule;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdElement getAdElement() {
        return this.adElement;
    }
    
    public void setAdElement(AdElement adElement) {
        this.adElement = adElement;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public AdReference getAdReferenceByAdReferenceValueId() {
        return this.adReferenceByAdReferenceValueId;
    }
    
    public void setAdReferenceByAdReferenceValueId(AdReference adReferenceByAdReferenceValueId) {
        this.adReferenceByAdReferenceValueId = adReferenceByAdReferenceValueId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public String getColumnname() {
        return this.columnname;
    }
    
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }
    public Long getFieldlength() {
        return this.fieldlength;
    }
    
    public void setFieldlength(Long fieldlength) {
        this.fieldlength = fieldlength;
    }
    public String getDefaultvalue() {
        return this.defaultvalue;
    }
    
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }
    public char getIskey() {
        return this.iskey;
    }
    
    public void setIskey(char iskey) {
        this.iskey = iskey;
    }
    public char getIsparent() {
        return this.isparent;
    }
    
    public void setIsparent(char isparent) {
        this.isparent = isparent;
    }
    public char getIsmandatory() {
        return this.ismandatory;
    }
    
    public void setIsmandatory(char ismandatory) {
        this.ismandatory = ismandatory;
    }
    public char getIsupdateable() {
        return this.isupdateable;
    }
    
    public void setIsupdateable(char isupdateable) {
        this.isupdateable = isupdateable;
    }
    public String getReadonlylogic() {
        return this.readonlylogic;
    }
    
    public void setReadonlylogic(String readonlylogic) {
        this.readonlylogic = readonlylogic;
    }
    public char getIsidentifier() {
        return this.isidentifier;
    }
    
    public void setIsidentifier(char isidentifier) {
        this.isidentifier = isidentifier;
    }
    public Long getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(Long seqno) {
        this.seqno = seqno;
    }
    public char getIstranslated() {
        return this.istranslated;
    }
    
    public void setIstranslated(char istranslated) {
        this.istranslated = istranslated;
    }
    public char getIsencrypted() {
        return this.isencrypted;
    }
    
    public void setIsencrypted(char isencrypted) {
        this.isencrypted = isencrypted;
    }
    public String getCallout() {
        return this.callout;
    }
    
    public void setCallout(String callout) {
        this.callout = callout;
    }
    public String getVformat() {
        return this.vformat;
    }
    
    public void setVformat(String vformat) {
        this.vformat = vformat;
    }
    public String getValuemin() {
        return this.valuemin;
    }
    
    public void setValuemin(String valuemin) {
        this.valuemin = valuemin;
    }
    public String getValuemax() {
        return this.valuemax;
    }
    
    public void setValuemax(String valuemax) {
        this.valuemax = valuemax;
    }
    public char getIsselectioncolumn() {
        return this.isselectioncolumn;
    }
    
    public void setIsselectioncolumn(char isselectioncolumn) {
        this.isselectioncolumn = isselectioncolumn;
    }
    public Character getIssyncdatabase() {
        return this.issyncdatabase;
    }
    
    public void setIssyncdatabase(Character issyncdatabase) {
        this.issyncdatabase = issyncdatabase;
    }
    public char getIsalwaysupdateable() {
        return this.isalwaysupdateable;
    }
    
    public void setIsalwaysupdateable(char isalwaysupdateable) {
        this.isalwaysupdateable = isalwaysupdateable;
    }
    public String getColumnsql() {
        return this.columnsql;
    }
    
    public void setColumnsql(String columnsql) {
        this.columnsql = columnsql;
    }
    public String getMandatorylogic() {
        return this.mandatorylogic;
    }
    
    public void setMandatorylogic(String mandatorylogic) {
        this.mandatorylogic = mandatorylogic;
    }
    public String getInfofactoryclass() {
        return this.infofactoryclass;
    }
    
    public void setInfofactoryclass(String infofactoryclass) {
        this.infofactoryclass = infofactoryclass;
    }
    public char getIsautocomplete() {
        return this.isautocomplete;
    }
    
    public void setIsautocomplete(char isautocomplete) {
        this.isautocomplete = isautocomplete;
    }
    public Character getIsallowlogging() {
        return this.isallowlogging;
    }
    
    public void setIsallowlogging(Character isallowlogging) {
        this.isallowlogging = isallowlogging;
    }
    public String getFormatpattern() {
        return this.formatpattern;
    }
    
    public void setFormatpattern(String formatpattern) {
        this.formatpattern = formatpattern;
    }
    public Set getAdWfNodes() {
        return this.adWfNodes;
    }
    
    public void setAdWfNodes(Set adWfNodes) {
        this.adWfNodes = adWfNodes;
    }
    public Set getAdWorkbenches() {
        return this.adWorkbenches;
    }
    
    public void setAdWorkbenches(Set adWorkbenches) {
        this.adWorkbenches = adWorkbenches;
    }




}


