package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdElement generated by hbm2java
 */
public class AdElement  implements java.io.Serializable {


     private long adElementId;
     private AdEntitytype adEntitytype;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String columnname;
     private String name;
     private String printname;
     private String description;
     private String help;
     private String poName;
     private String poPrintname;
     private String poDescription;
     private String poHelp;
     private Set adColumns = new HashSet(0);

    public AdElement() {
    }

	
    public AdElement(long adElementId, AdEntitytype adEntitytype, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String columnname, String name, String printname) {
        this.adElementId = adElementId;
        this.adEntitytype = adEntitytype;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.columnname = columnname;
        this.name = name;
        this.printname = printname;
    }
    public AdElement(long adElementId, AdEntitytype adEntitytype, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String columnname, String name, String printname, String description, String help, String poName, String poPrintname, String poDescription, String poHelp, Set adColumns) {
       this.adElementId = adElementId;
       this.adEntitytype = adEntitytype;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.columnname = columnname;
       this.name = name;
       this.printname = printname;
       this.description = description;
       this.help = help;
       this.poName = poName;
       this.poPrintname = poPrintname;
       this.poDescription = poDescription;
       this.poHelp = poHelp;
       this.adColumns = adColumns;
    }
   
    public long getAdElementId() {
        return this.adElementId;
    }
    
    public void setAdElementId(long adElementId) {
        this.adElementId = adElementId;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getColumnname() {
        return this.columnname;
    }
    
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPrintname() {
        return this.printname;
    }
    
    public void setPrintname(String printname) {
        this.printname = printname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public String getPoName() {
        return this.poName;
    }
    
    public void setPoName(String poName) {
        this.poName = poName;
    }
    public String getPoPrintname() {
        return this.poPrintname;
    }
    
    public void setPoPrintname(String poPrintname) {
        this.poPrintname = poPrintname;
    }
    public String getPoDescription() {
        return this.poDescription;
    }
    
    public void setPoDescription(String poDescription) {
        this.poDescription = poDescription;
    }
    public String getPoHelp() {
        return this.poHelp;
    }
    
    public void setPoHelp(String poHelp) {
        this.poHelp = poHelp;
    }
    public Set getAdColumns() {
        return this.adColumns;
    }
    
    public void setAdColumns(Set adColumns) {
        this.adColumns = adColumns;
    }




}


