package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdLanguage generated by hbm2java
 */
public class AdLanguage  implements java.io.Serializable {


     private String adLanguage;
     private AdClient adClient;
     private AdOrg adOrg;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String languageiso;
     private String countrycode;
     private char isbaselanguage;
     private char issystemlanguage;
     private Character processing;
     private long adLanguageId;
     private char isdecimalpoint;
     private String datepattern;
     private String timepattern;
     private Set CCountries = new HashSet(0);
     private Set adMenuTrls = new HashSet(0);
     private Set adClients = new HashSet(0);
     private Set CBpartners = new HashSet(0);

    public AdLanguage() {
    }

	
    public AdLanguage(String adLanguage, AdClient adClient, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isbaselanguage, char issystemlanguage, long adLanguageId, char isdecimalpoint) {
        this.adLanguage = adLanguage;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isbaselanguage = isbaselanguage;
        this.issystemlanguage = issystemlanguage;
        this.adLanguageId = adLanguageId;
        this.isdecimalpoint = isdecimalpoint;
    }
    public AdLanguage(String adLanguage, AdClient adClient, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String languageiso, String countrycode, char isbaselanguage, char issystemlanguage, Character processing, long adLanguageId, char isdecimalpoint, String datepattern, String timepattern, Set CCountries, Set adMenuTrls, Set adClients, Set CBpartners) {
       this.adLanguage = adLanguage;
       this.adClient = adClient;
       this.adOrg = adOrg;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.languageiso = languageiso;
       this.countrycode = countrycode;
       this.isbaselanguage = isbaselanguage;
       this.issystemlanguage = issystemlanguage;
       this.processing = processing;
       this.adLanguageId = adLanguageId;
       this.isdecimalpoint = isdecimalpoint;
       this.datepattern = datepattern;
       this.timepattern = timepattern;
       this.CCountries = CCountries;
       this.adMenuTrls = adMenuTrls;
       this.adClients = adClients;
       this.CBpartners = CBpartners;
    }
   
    public String getAdLanguage() {
        return this.adLanguage;
    }
    
    public void setAdLanguage(String adLanguage) {
        this.adLanguage = adLanguage;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLanguageiso() {
        return this.languageiso;
    }
    
    public void setLanguageiso(String languageiso) {
        this.languageiso = languageiso;
    }
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    public char getIsbaselanguage() {
        return this.isbaselanguage;
    }
    
    public void setIsbaselanguage(char isbaselanguage) {
        this.isbaselanguage = isbaselanguage;
    }
    public char getIssystemlanguage() {
        return this.issystemlanguage;
    }
    
    public void setIssystemlanguage(char issystemlanguage) {
        this.issystemlanguage = issystemlanguage;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public long getAdLanguageId() {
        return this.adLanguageId;
    }
    
    public void setAdLanguageId(long adLanguageId) {
        this.adLanguageId = adLanguageId;
    }
    public char getIsdecimalpoint() {
        return this.isdecimalpoint;
    }
    
    public void setIsdecimalpoint(char isdecimalpoint) {
        this.isdecimalpoint = isdecimalpoint;
    }
    public String getDatepattern() {
        return this.datepattern;
    }
    
    public void setDatepattern(String datepattern) {
        this.datepattern = datepattern;
    }
    public String getTimepattern() {
        return this.timepattern;
    }
    
    public void setTimepattern(String timepattern) {
        this.timepattern = timepattern;
    }
    public Set getCCountries() {
        return this.CCountries;
    }
    
    public void setCCountries(Set CCountries) {
        this.CCountries = CCountries;
    }
    public Set getAdMenuTrls() {
        return this.adMenuTrls;
    }
    
    public void setAdMenuTrls(Set adMenuTrls) {
        this.adMenuTrls = adMenuTrls;
    }
    public Set getAdClients() {
        return this.adClients;
    }
    
    public void setAdClients(Set adClients) {
        this.adClients = adClients;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }




}


