package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * AdMenuTrl generated by hbm2java
 */
public class AdMenuTrl  implements java.io.Serializable {


     private AdMenuTrlId id;
     private AdMenu adMenu;
     private AdLanguage adLanguage;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private char istranslated;

    public AdMenuTrl() {
    }

	
    public AdMenuTrl(AdMenuTrlId id, AdMenu adMenu, AdLanguage adLanguage, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char istranslated) {
        this.id = id;
        this.adMenu = adMenu;
        this.adLanguage = adLanguage;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.istranslated = istranslated;
    }
    public AdMenuTrl(AdMenuTrlId id, AdMenu adMenu, AdLanguage adLanguage, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, char istranslated) {
       this.id = id;
       this.adMenu = adMenu;
       this.adLanguage = adLanguage;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.istranslated = istranslated;
    }
   
    public AdMenuTrlId getId() {
        return this.id;
    }
    
    public void setId(AdMenuTrlId id) {
        this.id = id;
    }
    public AdMenu getAdMenu() {
        return this.adMenu;
    }
    
    public void setAdMenu(AdMenu adMenu) {
        this.adMenu = adMenu;
    }
    public AdLanguage getAdLanguage() {
        return this.adLanguage;
    }
    
    public void setAdLanguage(AdLanguage adLanguage) {
        this.adLanguage = adLanguage;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getIstranslated() {
        return this.istranslated;
    }
    
    public void setIstranslated(char istranslated) {
        this.istranslated = istranslated;
    }




}


