package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdPrintformat generated by hbm2java
 */
public class AdPrintformat  implements java.io.Serializable {


     private long adPrintformatId;
     private AdTable adTable;
     private AdProcess adProcess;
     private AdPrinttableformat adPrinttableformat;
     private AdPrintpaper adPrintpaper;
     private AdPrintcolor adPrintcolor;
     private AdReportview adReportview;
     private AdPrintfont adPrintfont;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private char istablebased;
     private char isform;
     private char isstandardheaderfooter;
     private long headermargin;
     private long footermargin;
     private Character createcopy;
     private String printername;
     private char isdefault;
     private String classname;
     private String args;
     private Set CBpartners = new HashSet(0);
     private Set adProcesses = new HashSet(0);

    public AdPrintformat() {
    }

	
    public AdPrintformat(long adPrintformatId, AdTable adTable, AdPrintpaper adPrintpaper, AdPrintcolor adPrintcolor, AdPrintfont adPrintfont, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char istablebased, char isform, char isstandardheaderfooter, long headermargin, long footermargin, char isdefault) {
        this.adPrintformatId = adPrintformatId;
        this.adTable = adTable;
        this.adPrintpaper = adPrintpaper;
        this.adPrintcolor = adPrintcolor;
        this.adPrintfont = adPrintfont;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.istablebased = istablebased;
        this.isform = isform;
        this.isstandardheaderfooter = isstandardheaderfooter;
        this.headermargin = headermargin;
        this.footermargin = footermargin;
        this.isdefault = isdefault;
    }
    public AdPrintformat(long adPrintformatId, AdTable adTable, AdProcess adProcess, AdPrinttableformat adPrinttableformat, AdPrintpaper adPrintpaper, AdPrintcolor adPrintcolor, AdReportview adReportview, AdPrintfont adPrintfont, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, char istablebased, char isform, char isstandardheaderfooter, long headermargin, long footermargin, Character createcopy, String printername, char isdefault, String classname, String args, Set CBpartners, Set adProcesses) {
       this.adPrintformatId = adPrintformatId;
       this.adTable = adTable;
       this.adProcess = adProcess;
       this.adPrinttableformat = adPrinttableformat;
       this.adPrintpaper = adPrintpaper;
       this.adPrintcolor = adPrintcolor;
       this.adReportview = adReportview;
       this.adPrintfont = adPrintfont;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.istablebased = istablebased;
       this.isform = isform;
       this.isstandardheaderfooter = isstandardheaderfooter;
       this.headermargin = headermargin;
       this.footermargin = footermargin;
       this.createcopy = createcopy;
       this.printername = printername;
       this.isdefault = isdefault;
       this.classname = classname;
       this.args = args;
       this.CBpartners = CBpartners;
       this.adProcesses = adProcesses;
    }
   
    public long getAdPrintformatId() {
        return this.adPrintformatId;
    }
    
    public void setAdPrintformatId(long adPrintformatId) {
        this.adPrintformatId = adPrintformatId;
    }
    public AdTable getAdTable() {
        return this.adTable;
    }
    
    public void setAdTable(AdTable adTable) {
        this.adTable = adTable;
    }
    public AdProcess getAdProcess() {
        return this.adProcess;
    }
    
    public void setAdProcess(AdProcess adProcess) {
        this.adProcess = adProcess;
    }
    public AdPrinttableformat getAdPrinttableformat() {
        return this.adPrinttableformat;
    }
    
    public void setAdPrinttableformat(AdPrinttableformat adPrinttableformat) {
        this.adPrinttableformat = adPrinttableformat;
    }
    public AdPrintpaper getAdPrintpaper() {
        return this.adPrintpaper;
    }
    
    public void setAdPrintpaper(AdPrintpaper adPrintpaper) {
        this.adPrintpaper = adPrintpaper;
    }
    public AdPrintcolor getAdPrintcolor() {
        return this.adPrintcolor;
    }
    
    public void setAdPrintcolor(AdPrintcolor adPrintcolor) {
        this.adPrintcolor = adPrintcolor;
    }
    public AdReportview getAdReportview() {
        return this.adReportview;
    }
    
    public void setAdReportview(AdReportview adReportview) {
        this.adReportview = adReportview;
    }
    public AdPrintfont getAdPrintfont() {
        return this.adPrintfont;
    }
    
    public void setAdPrintfont(AdPrintfont adPrintfont) {
        this.adPrintfont = adPrintfont;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getIstablebased() {
        return this.istablebased;
    }
    
    public void setIstablebased(char istablebased) {
        this.istablebased = istablebased;
    }
    public char getIsform() {
        return this.isform;
    }
    
    public void setIsform(char isform) {
        this.isform = isform;
    }
    public char getIsstandardheaderfooter() {
        return this.isstandardheaderfooter;
    }
    
    public void setIsstandardheaderfooter(char isstandardheaderfooter) {
        this.isstandardheaderfooter = isstandardheaderfooter;
    }
    public long getHeadermargin() {
        return this.headermargin;
    }
    
    public void setHeadermargin(long headermargin) {
        this.headermargin = headermargin;
    }
    public long getFootermargin() {
        return this.footermargin;
    }
    
    public void setFootermargin(long footermargin) {
        this.footermargin = footermargin;
    }
    public Character getCreatecopy() {
        return this.createcopy;
    }
    
    public void setCreatecopy(Character createcopy) {
        this.createcopy = createcopy;
    }
    public String getPrintername() {
        return this.printername;
    }
    
    public void setPrintername(String printername) {
        this.printername = printername;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }
    public String getArgs() {
        return this.args;
    }
    
    public void setArgs(String args) {
        this.args = args;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }
    public Set getAdProcesses() {
        return this.adProcesses;
    }
    
    public void setAdProcesses(Set adProcesses) {
        this.adProcesses = adProcesses;
    }




}


