package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdPrintcolor generated by hbm2java
 */
public class AdPrintcolor  implements java.io.Serializable {


     private long adPrintcolorId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private char isdefault;
     private String code;
     private Set CBpGroups = new HashSet(0);
     private Set adPrinttableformatsForFunctbgPrintcolorId = new HashSet(0);
     private Set adPrinttableformatsForHdrtextbgPrintcolorId = new HashSet(0);
     private Set MProductCategories = new HashSet(0);
     private Set adPrinttableformatsForFunctfgPrintcolorId = new HashSet(0);
     private Set adPrinttableformatsForHdrlinePrintcolorId = new HashSet(0);
     private Set adPrinttableformatsForHdrtextfgPrintcolorId = new HashSet(0);
     private Set adPrintformats = new HashSet(0);
     private Set adPrinttableformatsForLinePrintcolorId = new HashSet(0);

    public AdPrintcolor() {
    }

	
    public AdPrintcolor(long adPrintcolorId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isdefault, String code) {
        this.adPrintcolorId = adPrintcolorId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isdefault = isdefault;
        this.code = code;
    }
    public AdPrintcolor(long adPrintcolorId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isdefault, String code, Set CBpGroups, Set adPrinttableformatsForFunctbgPrintcolorId, Set adPrinttableformatsForHdrtextbgPrintcolorId, Set MProductCategories, Set adPrinttableformatsForFunctfgPrintcolorId, Set adPrinttableformatsForHdrlinePrintcolorId, Set adPrinttableformatsForHdrtextfgPrintcolorId, Set adPrintformats, Set adPrinttableformatsForLinePrintcolorId) {
       this.adPrintcolorId = adPrintcolorId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.isdefault = isdefault;
       this.code = code;
       this.CBpGroups = CBpGroups;
       this.adPrinttableformatsForFunctbgPrintcolorId = adPrinttableformatsForFunctbgPrintcolorId;
       this.adPrinttableformatsForHdrtextbgPrintcolorId = adPrinttableformatsForHdrtextbgPrintcolorId;
       this.MProductCategories = MProductCategories;
       this.adPrinttableformatsForFunctfgPrintcolorId = adPrinttableformatsForFunctfgPrintcolorId;
       this.adPrinttableformatsForHdrlinePrintcolorId = adPrinttableformatsForHdrlinePrintcolorId;
       this.adPrinttableformatsForHdrtextfgPrintcolorId = adPrinttableformatsForHdrtextfgPrintcolorId;
       this.adPrintformats = adPrintformats;
       this.adPrinttableformatsForLinePrintcolorId = adPrinttableformatsForLinePrintcolorId;
    }
   
    public long getAdPrintcolorId() {
        return this.adPrintcolorId;
    }
    
    public void setAdPrintcolorId(long adPrintcolorId) {
        this.adPrintcolorId = adPrintcolorId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getCBpGroups() {
        return this.CBpGroups;
    }
    
    public void setCBpGroups(Set CBpGroups) {
        this.CBpGroups = CBpGroups;
    }
    public Set getAdPrinttableformatsForFunctbgPrintcolorId() {
        return this.adPrinttableformatsForFunctbgPrintcolorId;
    }
    
    public void setAdPrinttableformatsForFunctbgPrintcolorId(Set adPrinttableformatsForFunctbgPrintcolorId) {
        this.adPrinttableformatsForFunctbgPrintcolorId = adPrinttableformatsForFunctbgPrintcolorId;
    }
    public Set getAdPrinttableformatsForHdrtextbgPrintcolorId() {
        return this.adPrinttableformatsForHdrtextbgPrintcolorId;
    }
    
    public void setAdPrinttableformatsForHdrtextbgPrintcolorId(Set adPrinttableformatsForHdrtextbgPrintcolorId) {
        this.adPrinttableformatsForHdrtextbgPrintcolorId = adPrinttableformatsForHdrtextbgPrintcolorId;
    }
    public Set getMProductCategories() {
        return this.MProductCategories;
    }
    
    public void setMProductCategories(Set MProductCategories) {
        this.MProductCategories = MProductCategories;
    }
    public Set getAdPrinttableformatsForFunctfgPrintcolorId() {
        return this.adPrinttableformatsForFunctfgPrintcolorId;
    }
    
    public void setAdPrinttableformatsForFunctfgPrintcolorId(Set adPrinttableformatsForFunctfgPrintcolorId) {
        this.adPrinttableformatsForFunctfgPrintcolorId = adPrinttableformatsForFunctfgPrintcolorId;
    }
    public Set getAdPrinttableformatsForHdrlinePrintcolorId() {
        return this.adPrinttableformatsForHdrlinePrintcolorId;
    }
    
    public void setAdPrinttableformatsForHdrlinePrintcolorId(Set adPrinttableformatsForHdrlinePrintcolorId) {
        this.adPrinttableformatsForHdrlinePrintcolorId = adPrinttableformatsForHdrlinePrintcolorId;
    }
    public Set getAdPrinttableformatsForHdrtextfgPrintcolorId() {
        return this.adPrinttableformatsForHdrtextfgPrintcolorId;
    }
    
    public void setAdPrinttableformatsForHdrtextfgPrintcolorId(Set adPrinttableformatsForHdrtextfgPrintcolorId) {
        this.adPrinttableformatsForHdrtextfgPrintcolorId = adPrinttableformatsForHdrtextfgPrintcolorId;
    }
    public Set getAdPrintformats() {
        return this.adPrintformats;
    }
    
    public void setAdPrintformats(Set adPrintformats) {
        this.adPrintformats = adPrintformats;
    }
    public Set getAdPrinttableformatsForLinePrintcolorId() {
        return this.adPrinttableformatsForLinePrintcolorId;
    }
    
    public void setAdPrinttableformatsForLinePrintcolorId(Set adPrinttableformatsForLinePrintcolorId) {
        this.adPrinttableformatsForLinePrintcolorId = adPrinttableformatsForLinePrintcolorId;
    }




}


