package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdReference generated by hbm2java
 */
public class AdReference  implements java.io.Serializable {


     private long adReferenceId;
     private AdClient adClient;
     private AdOrg adOrg;
     private AdEntitytype adEntitytype;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private char validationtype;
     private String vformat;
     private Character isorderbyvalue;
     private Set adColumnsForAdReferenceId = new HashSet(0);
     private Set adColumnsForAdReferenceValueId = new HashSet(0);

    public AdReference() {
    }

	
    public AdReference(long adReferenceId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char validationtype) {
        this.adReferenceId = adReferenceId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.validationtype = validationtype;
    }
    public AdReference(long adReferenceId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, char validationtype, String vformat, Character isorderbyvalue, Set adColumnsForAdReferenceId, Set adColumnsForAdReferenceValueId) {
       this.adReferenceId = adReferenceId;
       this.adClient = adClient;
       this.adOrg = adOrg;
       this.adEntitytype = adEntitytype;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.validationtype = validationtype;
       this.vformat = vformat;
       this.isorderbyvalue = isorderbyvalue;
       this.adColumnsForAdReferenceId = adColumnsForAdReferenceId;
       this.adColumnsForAdReferenceValueId = adColumnsForAdReferenceValueId;
    }
   
    public long getAdReferenceId() {
        return this.adReferenceId;
    }
    
    public void setAdReferenceId(long adReferenceId) {
        this.adReferenceId = adReferenceId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public char getValidationtype() {
        return this.validationtype;
    }
    
    public void setValidationtype(char validationtype) {
        this.validationtype = validationtype;
    }
    public String getVformat() {
        return this.vformat;
    }
    
    public void setVformat(String vformat) {
        this.vformat = vformat;
    }
    public Character getIsorderbyvalue() {
        return this.isorderbyvalue;
    }
    
    public void setIsorderbyvalue(Character isorderbyvalue) {
        this.isorderbyvalue = isorderbyvalue;
    }
    public Set getAdColumnsForAdReferenceId() {
        return this.adColumnsForAdReferenceId;
    }
    
    public void setAdColumnsForAdReferenceId(Set adColumnsForAdReferenceId) {
        this.adColumnsForAdReferenceId = adColumnsForAdReferenceId;
    }
    public Set getAdColumnsForAdReferenceValueId() {
        return this.adColumnsForAdReferenceValueId;
    }
    
    public void setAdColumnsForAdReferenceValueId(Set adColumnsForAdReferenceValueId) {
        this.adColumnsForAdReferenceValueId = adColumnsForAdReferenceValueId;
    }




}


