package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdReplicationstrategy generated by hbm2java
 */
public class AdReplicationstrategy  implements java.io.Serializable {


     private long adReplicationstrategyId;
     private AdEntitytype adEntitytype;
     private ExpProcessor expProcessor;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private String value;
     private Set adClients = new HashSet(0);
     private Set adOrgs = new HashSet(0);

    public AdReplicationstrategy() {
    }

	
    public AdReplicationstrategy(long adReplicationstrategyId, AdEntitytype adEntitytype, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name) {
        this.adReplicationstrategyId = adReplicationstrategyId;
        this.adEntitytype = adEntitytype;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
    }
    public AdReplicationstrategy(long adReplicationstrategyId, AdEntitytype adEntitytype, ExpProcessor expProcessor, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, String value, Set adClients, Set adOrgs) {
       this.adReplicationstrategyId = adReplicationstrategyId;
       this.adEntitytype = adEntitytype;
       this.expProcessor = expProcessor;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.value = value;
       this.adClients = adClients;
       this.adOrgs = adOrgs;
    }
   
    public long getAdReplicationstrategyId() {
        return this.adReplicationstrategyId;
    }
    
    public void setAdReplicationstrategyId(long adReplicationstrategyId) {
        this.adReplicationstrategyId = adReplicationstrategyId;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public ExpProcessor getExpProcessor() {
        return this.expProcessor;
    }
    
    public void setExpProcessor(ExpProcessor expProcessor) {
        this.expProcessor = expProcessor;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getAdClients() {
        return this.adClients;
    }
    
    public void setAdClients(Set adClients) {
        this.adClients = adClients;
    }
    public Set getAdOrgs() {
        return this.adOrgs;
    }
    
    public void setAdOrgs(Set adOrgs) {
        this.adOrgs = adOrgs;
    }




}


