package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdRole generated by hbm2java
 */
public class AdRole  implements java.io.Serializable {


     private long adRoleId;
     private AdTree adTreeByAdTreeOrgId;
     private AdClient adClient;
     private CCurrency CCurrency;
     private AdTree adTreeByAdTreeMenuId;
     private AdOrg adOrg;
     private AdUser adUser;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private String name;
     private long updatedby;
     private String description;
     private String userlevel;
     private BigDecimal amtapproval;
     private char ismanual;
     private char isshowacct;
     private char ispersonallock;
     private char ispersonalaccess;
     private char iscanexport;
     private char iscanreport;
     private char iscanapproveowndoc;
     private char isaccessallorgs;
     private char ischangelog;
     private char preferencetype;
     private char overwritepricelimit;
     private char isuseuserorgaccess;
     private long confirmqueryrecords;
     private long maxqueryrecords;
     private Character connectionprofile;
     private char allowInfoAccount;
     private char allowInfoAsset;
     private char allowInfoBpartner;
     private char allowInfoCashjournal;
     private char allowInfoInout;
     private char allowInfoInvoice;
     private char allowInfoOrder;
     private char allowInfoPayment;
     private char allowInfoProduct;
     private char allowInfoResource;
     private char allowInfoSchedule;
     private BigDecimal userdiscount;
     private char allowInfoMrp;
     private char allowInfoCrp;
     private char isdiscountuptolimitprice;
     private char isdiscountallowedontotal;
     private Set adWfResponsibles = new HashSet(0);
     private Set adRoleIncludedsForAdRoleId = new HashSet(0);
     private Set adRoleOrgaccesses = new HashSet(0);
     private Set adRoleIncludedsForIncludedRoleId = new HashSet(0);
     private Set adUserRoleses = new HashSet(0);

    public AdRole() {
    }

	
    public AdRole(long adRoleId, AdClient adClient, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, String name, long updatedby, String userlevel, char ismanual, char isshowacct, char ispersonallock, char ispersonalaccess, char iscanexport, char iscanreport, char iscanapproveowndoc, char isaccessallorgs, char ischangelog, char preferencetype, char overwritepricelimit, char isuseuserorgaccess, long confirmqueryrecords, long maxqueryrecords, char allowInfoAccount, char allowInfoAsset, char allowInfoBpartner, char allowInfoCashjournal, char allowInfoInout, char allowInfoInvoice, char allowInfoOrder, char allowInfoPayment, char allowInfoProduct, char allowInfoResource, char allowInfoSchedule, char allowInfoMrp, char allowInfoCrp, char isdiscountuptolimitprice, char isdiscountallowedontotal) {
        this.adRoleId = adRoleId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.name = name;
        this.updatedby = updatedby;
        this.userlevel = userlevel;
        this.ismanual = ismanual;
        this.isshowacct = isshowacct;
        this.ispersonallock = ispersonallock;
        this.ispersonalaccess = ispersonalaccess;
        this.iscanexport = iscanexport;
        this.iscanreport = iscanreport;
        this.iscanapproveowndoc = iscanapproveowndoc;
        this.isaccessallorgs = isaccessallorgs;
        this.ischangelog = ischangelog;
        this.preferencetype = preferencetype;
        this.overwritepricelimit = overwritepricelimit;
        this.isuseuserorgaccess = isuseuserorgaccess;
        this.confirmqueryrecords = confirmqueryrecords;
        this.maxqueryrecords = maxqueryrecords;
        this.allowInfoAccount = allowInfoAccount;
        this.allowInfoAsset = allowInfoAsset;
        this.allowInfoBpartner = allowInfoBpartner;
        this.allowInfoCashjournal = allowInfoCashjournal;
        this.allowInfoInout = allowInfoInout;
        this.allowInfoInvoice = allowInfoInvoice;
        this.allowInfoOrder = allowInfoOrder;
        this.allowInfoPayment = allowInfoPayment;
        this.allowInfoProduct = allowInfoProduct;
        this.allowInfoResource = allowInfoResource;
        this.allowInfoSchedule = allowInfoSchedule;
        this.allowInfoMrp = allowInfoMrp;
        this.allowInfoCrp = allowInfoCrp;
        this.isdiscountuptolimitprice = isdiscountuptolimitprice;
        this.isdiscountallowedontotal = isdiscountallowedontotal;
    }
    public AdRole(long adRoleId, AdTree adTreeByAdTreeOrgId, AdClient adClient, CCurrency CCurrency, AdTree adTreeByAdTreeMenuId, AdOrg adOrg, AdUser adUser, char isactive, Date created, long createdby, Date updated, String name, long updatedby, String description, String userlevel, BigDecimal amtapproval, char ismanual, char isshowacct, char ispersonallock, char ispersonalaccess, char iscanexport, char iscanreport, char iscanapproveowndoc, char isaccessallorgs, char ischangelog, char preferencetype, char overwritepricelimit, char isuseuserorgaccess, long confirmqueryrecords, long maxqueryrecords, Character connectionprofile, char allowInfoAccount, char allowInfoAsset, char allowInfoBpartner, char allowInfoCashjournal, char allowInfoInout, char allowInfoInvoice, char allowInfoOrder, char allowInfoPayment, char allowInfoProduct, char allowInfoResource, char allowInfoSchedule, BigDecimal userdiscount, char allowInfoMrp, char allowInfoCrp, char isdiscountuptolimitprice, char isdiscountallowedontotal, Set adWfResponsibles, Set adRoleIncludedsForAdRoleId, Set adRoleOrgaccesses, Set adRoleIncludedsForIncludedRoleId, Set adUserRoleses) {
       this.adRoleId = adRoleId;
       this.adTreeByAdTreeOrgId = adTreeByAdTreeOrgId;
       this.adClient = adClient;
       this.CCurrency = CCurrency;
       this.adTreeByAdTreeMenuId = adTreeByAdTreeMenuId;
       this.adOrg = adOrg;
       this.adUser = adUser;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.name = name;
       this.updatedby = updatedby;
       this.description = description;
       this.userlevel = userlevel;
       this.amtapproval = amtapproval;
       this.ismanual = ismanual;
       this.isshowacct = isshowacct;
       this.ispersonallock = ispersonallock;
       this.ispersonalaccess = ispersonalaccess;
       this.iscanexport = iscanexport;
       this.iscanreport = iscanreport;
       this.iscanapproveowndoc = iscanapproveowndoc;
       this.isaccessallorgs = isaccessallorgs;
       this.ischangelog = ischangelog;
       this.preferencetype = preferencetype;
       this.overwritepricelimit = overwritepricelimit;
       this.isuseuserorgaccess = isuseuserorgaccess;
       this.confirmqueryrecords = confirmqueryrecords;
       this.maxqueryrecords = maxqueryrecords;
       this.connectionprofile = connectionprofile;
       this.allowInfoAccount = allowInfoAccount;
       this.allowInfoAsset = allowInfoAsset;
       this.allowInfoBpartner = allowInfoBpartner;
       this.allowInfoCashjournal = allowInfoCashjournal;
       this.allowInfoInout = allowInfoInout;
       this.allowInfoInvoice = allowInfoInvoice;
       this.allowInfoOrder = allowInfoOrder;
       this.allowInfoPayment = allowInfoPayment;
       this.allowInfoProduct = allowInfoProduct;
       this.allowInfoResource = allowInfoResource;
       this.allowInfoSchedule = allowInfoSchedule;
       this.userdiscount = userdiscount;
       this.allowInfoMrp = allowInfoMrp;
       this.allowInfoCrp = allowInfoCrp;
       this.isdiscountuptolimitprice = isdiscountuptolimitprice;
       this.isdiscountallowedontotal = isdiscountallowedontotal;
       this.adWfResponsibles = adWfResponsibles;
       this.adRoleIncludedsForAdRoleId = adRoleIncludedsForAdRoleId;
       this.adRoleOrgaccesses = adRoleOrgaccesses;
       this.adRoleIncludedsForIncludedRoleId = adRoleIncludedsForIncludedRoleId;
       this.adUserRoleses = adUserRoleses;
    }
   
    public long getAdRoleId() {
        return this.adRoleId;
    }
    
    public void setAdRoleId(long adRoleId) {
        this.adRoleId = adRoleId;
    }
    public AdTree getAdTreeByAdTreeOrgId() {
        return this.adTreeByAdTreeOrgId;
    }
    
    public void setAdTreeByAdTreeOrgId(AdTree adTreeByAdTreeOrgId) {
        this.adTreeByAdTreeOrgId = adTreeByAdTreeOrgId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CCurrency getCCurrency() {
        return this.CCurrency;
    }
    
    public void setCCurrency(CCurrency CCurrency) {
        this.CCurrency = CCurrency;
    }
    public AdTree getAdTreeByAdTreeMenuId() {
        return this.adTreeByAdTreeMenuId;
    }
    
    public void setAdTreeByAdTreeMenuId(AdTree adTreeByAdTreeMenuId) {
        this.adTreeByAdTreeMenuId = adTreeByAdTreeMenuId;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdUser getAdUser() {
        return this.adUser;
    }
    
    public void setAdUser(AdUser adUser) {
        this.adUser = adUser;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUserlevel() {
        return this.userlevel;
    }
    
    public void setUserlevel(String userlevel) {
        this.userlevel = userlevel;
    }
    public BigDecimal getAmtapproval() {
        return this.amtapproval;
    }
    
    public void setAmtapproval(BigDecimal amtapproval) {
        this.amtapproval = amtapproval;
    }
    public char getIsmanual() {
        return this.ismanual;
    }
    
    public void setIsmanual(char ismanual) {
        this.ismanual = ismanual;
    }
    public char getIsshowacct() {
        return this.isshowacct;
    }
    
    public void setIsshowacct(char isshowacct) {
        this.isshowacct = isshowacct;
    }
    public char getIspersonallock() {
        return this.ispersonallock;
    }
    
    public void setIspersonallock(char ispersonallock) {
        this.ispersonallock = ispersonallock;
    }
    public char getIspersonalaccess() {
        return this.ispersonalaccess;
    }
    
    public void setIspersonalaccess(char ispersonalaccess) {
        this.ispersonalaccess = ispersonalaccess;
    }
    public char getIscanexport() {
        return this.iscanexport;
    }
    
    public void setIscanexport(char iscanexport) {
        this.iscanexport = iscanexport;
    }
    public char getIscanreport() {
        return this.iscanreport;
    }
    
    public void setIscanreport(char iscanreport) {
        this.iscanreport = iscanreport;
    }
    public char getIscanapproveowndoc() {
        return this.iscanapproveowndoc;
    }
    
    public void setIscanapproveowndoc(char iscanapproveowndoc) {
        this.iscanapproveowndoc = iscanapproveowndoc;
    }
    public char getIsaccessallorgs() {
        return this.isaccessallorgs;
    }
    
    public void setIsaccessallorgs(char isaccessallorgs) {
        this.isaccessallorgs = isaccessallorgs;
    }
    public char getIschangelog() {
        return this.ischangelog;
    }
    
    public void setIschangelog(char ischangelog) {
        this.ischangelog = ischangelog;
    }
    public char getPreferencetype() {
        return this.preferencetype;
    }
    
    public void setPreferencetype(char preferencetype) {
        this.preferencetype = preferencetype;
    }
    public char getOverwritepricelimit() {
        return this.overwritepricelimit;
    }
    
    public void setOverwritepricelimit(char overwritepricelimit) {
        this.overwritepricelimit = overwritepricelimit;
    }
    public char getIsuseuserorgaccess() {
        return this.isuseuserorgaccess;
    }
    
    public void setIsuseuserorgaccess(char isuseuserorgaccess) {
        this.isuseuserorgaccess = isuseuserorgaccess;
    }
    public long getConfirmqueryrecords() {
        return this.confirmqueryrecords;
    }
    
    public void setConfirmqueryrecords(long confirmqueryrecords) {
        this.confirmqueryrecords = confirmqueryrecords;
    }
    public long getMaxqueryrecords() {
        return this.maxqueryrecords;
    }
    
    public void setMaxqueryrecords(long maxqueryrecords) {
        this.maxqueryrecords = maxqueryrecords;
    }
    public Character getConnectionprofile() {
        return this.connectionprofile;
    }
    
    public void setConnectionprofile(Character connectionprofile) {
        this.connectionprofile = connectionprofile;
    }
    public char getAllowInfoAccount() {
        return this.allowInfoAccount;
    }
    
    public void setAllowInfoAccount(char allowInfoAccount) {
        this.allowInfoAccount = allowInfoAccount;
    }
    public char getAllowInfoAsset() {
        return this.allowInfoAsset;
    }
    
    public void setAllowInfoAsset(char allowInfoAsset) {
        this.allowInfoAsset = allowInfoAsset;
    }
    public char getAllowInfoBpartner() {
        return this.allowInfoBpartner;
    }
    
    public void setAllowInfoBpartner(char allowInfoBpartner) {
        this.allowInfoBpartner = allowInfoBpartner;
    }
    public char getAllowInfoCashjournal() {
        return this.allowInfoCashjournal;
    }
    
    public void setAllowInfoCashjournal(char allowInfoCashjournal) {
        this.allowInfoCashjournal = allowInfoCashjournal;
    }
    public char getAllowInfoInout() {
        return this.allowInfoInout;
    }
    
    public void setAllowInfoInout(char allowInfoInout) {
        this.allowInfoInout = allowInfoInout;
    }
    public char getAllowInfoInvoice() {
        return this.allowInfoInvoice;
    }
    
    public void setAllowInfoInvoice(char allowInfoInvoice) {
        this.allowInfoInvoice = allowInfoInvoice;
    }
    public char getAllowInfoOrder() {
        return this.allowInfoOrder;
    }
    
    public void setAllowInfoOrder(char allowInfoOrder) {
        this.allowInfoOrder = allowInfoOrder;
    }
    public char getAllowInfoPayment() {
        return this.allowInfoPayment;
    }
    
    public void setAllowInfoPayment(char allowInfoPayment) {
        this.allowInfoPayment = allowInfoPayment;
    }
    public char getAllowInfoProduct() {
        return this.allowInfoProduct;
    }
    
    public void setAllowInfoProduct(char allowInfoProduct) {
        this.allowInfoProduct = allowInfoProduct;
    }
    public char getAllowInfoResource() {
        return this.allowInfoResource;
    }
    
    public void setAllowInfoResource(char allowInfoResource) {
        this.allowInfoResource = allowInfoResource;
    }
    public char getAllowInfoSchedule() {
        return this.allowInfoSchedule;
    }
    
    public void setAllowInfoSchedule(char allowInfoSchedule) {
        this.allowInfoSchedule = allowInfoSchedule;
    }
    public BigDecimal getUserdiscount() {
        return this.userdiscount;
    }
    
    public void setUserdiscount(BigDecimal userdiscount) {
        this.userdiscount = userdiscount;
    }
    public char getAllowInfoMrp() {
        return this.allowInfoMrp;
    }
    
    public void setAllowInfoMrp(char allowInfoMrp) {
        this.allowInfoMrp = allowInfoMrp;
    }
    public char getAllowInfoCrp() {
        return this.allowInfoCrp;
    }
    
    public void setAllowInfoCrp(char allowInfoCrp) {
        this.allowInfoCrp = allowInfoCrp;
    }
    public char getIsdiscountuptolimitprice() {
        return this.isdiscountuptolimitprice;
    }
    
    public void setIsdiscountuptolimitprice(char isdiscountuptolimitprice) {
        this.isdiscountuptolimitprice = isdiscountuptolimitprice;
    }
    public char getIsdiscountallowedontotal() {
        return this.isdiscountallowedontotal;
    }
    
    public void setIsdiscountallowedontotal(char isdiscountallowedontotal) {
        this.isdiscountallowedontotal = isdiscountallowedontotal;
    }
    public Set getAdWfResponsibles() {
        return this.adWfResponsibles;
    }
    
    public void setAdWfResponsibles(Set adWfResponsibles) {
        this.adWfResponsibles = adWfResponsibles;
    }
    public Set getAdRoleIncludedsForAdRoleId() {
        return this.adRoleIncludedsForAdRoleId;
    }
    
    public void setAdRoleIncludedsForAdRoleId(Set adRoleIncludedsForAdRoleId) {
        this.adRoleIncludedsForAdRoleId = adRoleIncludedsForAdRoleId;
    }
    public Set getAdRoleOrgaccesses() {
        return this.adRoleOrgaccesses;
    }
    
    public void setAdRoleOrgaccesses(Set adRoleOrgaccesses) {
        this.adRoleOrgaccesses = adRoleOrgaccesses;
    }
    public Set getAdRoleIncludedsForIncludedRoleId() {
        return this.adRoleIncludedsForIncludedRoleId;
    }
    
    public void setAdRoleIncludedsForIncludedRoleId(Set adRoleIncludedsForIncludedRoleId) {
        this.adRoleIncludedsForIncludedRoleId = adRoleIncludedsForIncludedRoleId;
    }
    public Set getAdUserRoleses() {
        return this.adUserRoleses;
    }
    
    public void setAdUserRoleses(Set adUserRoleses) {
        this.adUserRoleses = adUserRoleses;
    }




}


