package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdTask generated by hbm2java
 */
public class AdTask  implements java.io.Serializable {


     private long adTaskId;
     private AdClient adClient;
     private AdOrg adOrg;
     private AdEntitytype adEntitytype;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private char accesslevel;
     private String osCommand;
     private char isserverprocess;
     private Set adWfNodes = new HashSet(0);
     private Set adMenus = new HashSet(0);

    public AdTask() {
    }

	
    public AdTask(long adTaskId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char accesslevel, String osCommand, char isserverprocess) {
        this.adTaskId = adTaskId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.accesslevel = accesslevel;
        this.osCommand = osCommand;
        this.isserverprocess = isserverprocess;
    }
    public AdTask(long adTaskId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, char accesslevel, String osCommand, char isserverprocess, Set adWfNodes, Set adMenus) {
       this.adTaskId = adTaskId;
       this.adClient = adClient;
       this.adOrg = adOrg;
       this.adEntitytype = adEntitytype;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.accesslevel = accesslevel;
       this.osCommand = osCommand;
       this.isserverprocess = isserverprocess;
       this.adWfNodes = adWfNodes;
       this.adMenus = adMenus;
    }
   
    public long getAdTaskId() {
        return this.adTaskId;
    }
    
    public void setAdTaskId(long adTaskId) {
        this.adTaskId = adTaskId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public char getAccesslevel() {
        return this.accesslevel;
    }
    
    public void setAccesslevel(char accesslevel) {
        this.accesslevel = accesslevel;
    }
    public String getOsCommand() {
        return this.osCommand;
    }
    
    public void setOsCommand(String osCommand) {
        this.osCommand = osCommand;
    }
    public char getIsserverprocess() {
        return this.isserverprocess;
    }
    
    public void setIsserverprocess(char isserverprocess) {
        this.isserverprocess = isserverprocess;
    }
    public Set getAdWfNodes() {
        return this.adWfNodes;
    }
    
    public void setAdWfNodes(Set adWfNodes) {
        this.adWfNodes = adWfNodes;
    }
    public Set getAdMenus() {
        return this.adMenus;
    }
    
    public void setAdMenus(Set adMenus) {
        this.adMenus = adMenus;
    }




}


