package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdTree generated by hbm2java
 */
public class AdTree  implements java.io.Serializable {


     private long adTreeId;
     private long adClientId;
     private long adOrgId;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private char isactive;
     private String name;
     private String description;
     private String treetype;
     private char isallnodes;
     private Character processing;
     private char isdefault;
     private Set adRolesForAdTreeMenuId = new HashSet(0);
     private Set adRolesForAdTreeOrgId = new HashSet(0);

    public AdTree() {
    }

	
    public AdTree(long adTreeId, long adClientId, long adOrgId, Date created, long createdby, Date updated, long updatedby, char isactive, String name, String treetype, char isallnodes, char isdefault) {
        this.adTreeId = adTreeId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.isactive = isactive;
        this.name = name;
        this.treetype = treetype;
        this.isallnodes = isallnodes;
        this.isdefault = isdefault;
    }
    public AdTree(long adTreeId, long adClientId, long adOrgId, Date created, long createdby, Date updated, long updatedby, char isactive, String name, String description, String treetype, char isallnodes, Character processing, char isdefault, Set adRolesForAdTreeMenuId, Set adRolesForAdTreeOrgId) {
       this.adTreeId = adTreeId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.isactive = isactive;
       this.name = name;
       this.description = description;
       this.treetype = treetype;
       this.isallnodes = isallnodes;
       this.processing = processing;
       this.isdefault = isdefault;
       this.adRolesForAdTreeMenuId = adRolesForAdTreeMenuId;
       this.adRolesForAdTreeOrgId = adRolesForAdTreeOrgId;
    }
   
    public long getAdTreeId() {
        return this.adTreeId;
    }
    
    public void setAdTreeId(long adTreeId) {
        this.adTreeId = adTreeId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTreetype() {
        return this.treetype;
    }
    
    public void setTreetype(String treetype) {
        this.treetype = treetype;
    }
    public char getIsallnodes() {
        return this.isallnodes;
    }
    
    public void setIsallnodes(char isallnodes) {
        this.isallnodes = isallnodes;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Set getAdRolesForAdTreeMenuId() {
        return this.adRolesForAdTreeMenuId;
    }
    
    public void setAdRolesForAdTreeMenuId(Set adRolesForAdTreeMenuId) {
        this.adRolesForAdTreeMenuId = adRolesForAdTreeMenuId;
    }
    public Set getAdRolesForAdTreeOrgId() {
        return this.adRolesForAdTreeOrgId;
    }
    
    public void setAdRolesForAdTreeOrgId(Set adRolesForAdTreeOrgId) {
        this.adRolesForAdTreeOrgId = adRolesForAdTreeOrgId;
    }




}


