package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0



/**
 * AdUserRolesId generated by hbm2java
 */
public class AdUserRolesId  implements java.io.Serializable {


     private long adUserId;
     private long adRoleId;

    public AdUserRolesId() {
    }

    public AdUserRolesId(long adUserId, long adRoleId) {
       this.adUserId = adUserId;
       this.adRoleId = adRoleId;
    }
   
    public long getAdUserId() {
        return this.adUserId;
    }
    
    public void setAdUserId(long adUserId) {
        this.adUserId = adUserId;
    }
    public long getAdRoleId() {
        return this.adRoleId;
    }
    
    public void setAdRoleId(long adRoleId) {
        this.adRoleId = adRoleId;
    }




}


