package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdUser generated by hbm2java
 */
public class AdUser  implements java.io.Serializable {


     private long adUserId;
     private CJob CJob;
     private CGreeting CGreeting;
     private CBpartner CBpartner;
     private CBpartnerLocation CBpartnerLocation;
     private AdClient adClient;
     private AdOrg adOrgByAdOrgtrxId;
     private AdOrg adOrgByAdOrgId;
     private AdUser adUser;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String password;
     private String email;
     private Character processing;
     private String emailuser;
     private String emailuserpw;
     private String title;
     private String comments;
     private String phone;
     private String phone2;
     private String fax;
     private Date lastcontact;
     private String lastresult;
     private Date birthday;
     private String emailverify;
     private Date emailverifydate;
     private char notificationtype;
     private char isfullbpaccess;
     private String ldapuser;
     private Character connectionprofile;
     private String value;
     private String userpin;
     private char isinpayroll;
     private Set adWorkflowprocessors = new HashSet(0);
     private Set adRoles = new HashSet(0);
     private Set CBpartners = new HashSet(0);
     private Set adUserOrgaccesses = new HashSet(0);
     private Set adUserRoleses = new HashSet(0);
     private Set CSalesregions = new HashSet(0);
     private Set adUsers = new HashSet(0);
     private Set adWfResponsibles = new HashSet(0);
     private Set SResources = new HashSet(0);

    public AdUser() {
    }

	
    public AdUser(long adUserId, AdClient adClient, AdOrg adOrgByAdOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char notificationtype, char isfullbpaccess, char isinpayroll) {
        this.adUserId = adUserId;
        this.adClient = adClient;
        this.adOrgByAdOrgId = adOrgByAdOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.notificationtype = notificationtype;
        this.isfullbpaccess = isfullbpaccess;
        this.isinpayroll = isinpayroll;
    }
    public AdUser(long adUserId, CJob CJob, CGreeting CGreeting, CBpartner CBpartner, CBpartnerLocation CBpartnerLocation, AdClient adClient, AdOrg adOrgByAdOrgtrxId, AdOrg adOrgByAdOrgId, AdUser adUser, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String password, String email, Character processing, String emailuser, String emailuserpw, String title, String comments, String phone, String phone2, String fax, Date lastcontact, String lastresult, Date birthday, String emailverify, Date emailverifydate, char notificationtype, char isfullbpaccess, String ldapuser, Character connectionprofile, String value, String userpin, char isinpayroll, Set adWorkflowprocessors, Set adRoles, Set CBpartners, Set adUserOrgaccesses, Set adUserRoleses, Set CSalesregions, Set adUsers, Set adWfResponsibles, Set SResources) {
       this.adUserId = adUserId;
       this.CJob = CJob;
       this.CGreeting = CGreeting;
       this.CBpartner = CBpartner;
       this.CBpartnerLocation = CBpartnerLocation;
       this.adClient = adClient;
       this.adOrgByAdOrgtrxId = adOrgByAdOrgtrxId;
       this.adOrgByAdOrgId = adOrgByAdOrgId;
       this.adUser = adUser;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.password = password;
       this.email = email;
       this.processing = processing;
       this.emailuser = emailuser;
       this.emailuserpw = emailuserpw;
       this.title = title;
       this.comments = comments;
       this.phone = phone;
       this.phone2 = phone2;
       this.fax = fax;
       this.lastcontact = lastcontact;
       this.lastresult = lastresult;
       this.birthday = birthday;
       this.emailverify = emailverify;
       this.emailverifydate = emailverifydate;
       this.notificationtype = notificationtype;
       this.isfullbpaccess = isfullbpaccess;
       this.ldapuser = ldapuser;
       this.connectionprofile = connectionprofile;
       this.value = value;
       this.userpin = userpin;
       this.isinpayroll = isinpayroll;
       this.adWorkflowprocessors = adWorkflowprocessors;
       this.adRoles = adRoles;
       this.CBpartners = CBpartners;
       this.adUserOrgaccesses = adUserOrgaccesses;
       this.adUserRoleses = adUserRoleses;
       this.CSalesregions = CSalesregions;
       this.adUsers = adUsers;
       this.adWfResponsibles = adWfResponsibles;
       this.SResources = SResources;
    }
   
    public long getAdUserId() {
        return this.adUserId;
    }
    
    public void setAdUserId(long adUserId) {
        this.adUserId = adUserId;
    }
    public CJob getCJob() {
        return this.CJob;
    }
    
    public void setCJob(CJob CJob) {
        this.CJob = CJob;
    }
    public CGreeting getCGreeting() {
        return this.CGreeting;
    }
    
    public void setCGreeting(CGreeting CGreeting) {
        this.CGreeting = CGreeting;
    }
    public CBpartner getCBpartner() {
        return this.CBpartner;
    }
    
    public void setCBpartner(CBpartner CBpartner) {
        this.CBpartner = CBpartner;
    }
    public CBpartnerLocation getCBpartnerLocation() {
        return this.CBpartnerLocation;
    }
    
    public void setCBpartnerLocation(CBpartnerLocation CBpartnerLocation) {
        this.CBpartnerLocation = CBpartnerLocation;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrgByAdOrgtrxId() {
        return this.adOrgByAdOrgtrxId;
    }
    
    public void setAdOrgByAdOrgtrxId(AdOrg adOrgByAdOrgtrxId) {
        this.adOrgByAdOrgtrxId = adOrgByAdOrgtrxId;
    }
    public AdOrg getAdOrgByAdOrgId() {
        return this.adOrgByAdOrgId;
    }
    
    public void setAdOrgByAdOrgId(AdOrg adOrgByAdOrgId) {
        this.adOrgByAdOrgId = adOrgByAdOrgId;
    }
    public AdUser getAdUser() {
        return this.adUser;
    }
    
    public void setAdUser(AdUser adUser) {
        this.adUser = adUser;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public String getEmailuser() {
        return this.emailuser;
    }
    
    public void setEmailuser(String emailuser) {
        this.emailuser = emailuser;
    }
    public String getEmailuserpw() {
        return this.emailuserpw;
    }
    
    public void setEmailuserpw(String emailuserpw) {
        this.emailuserpw = emailuserpw;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public Date getLastcontact() {
        return this.lastcontact;
    }
    
    public void setLastcontact(Date lastcontact) {
        this.lastcontact = lastcontact;
    }
    public String getLastresult() {
        return this.lastresult;
    }
    
    public void setLastresult(String lastresult) {
        this.lastresult = lastresult;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getEmailverify() {
        return this.emailverify;
    }
    
    public void setEmailverify(String emailverify) {
        this.emailverify = emailverify;
    }
    public Date getEmailverifydate() {
        return this.emailverifydate;
    }
    
    public void setEmailverifydate(Date emailverifydate) {
        this.emailverifydate = emailverifydate;
    }
    public char getNotificationtype() {
        return this.notificationtype;
    }
    
    public void setNotificationtype(char notificationtype) {
        this.notificationtype = notificationtype;
    }
    public char getIsfullbpaccess() {
        return this.isfullbpaccess;
    }
    
    public void setIsfullbpaccess(char isfullbpaccess) {
        this.isfullbpaccess = isfullbpaccess;
    }
    public String getLdapuser() {
        return this.ldapuser;
    }
    
    public void setLdapuser(String ldapuser) {
        this.ldapuser = ldapuser;
    }
    public Character getConnectionprofile() {
        return this.connectionprofile;
    }
    
    public void setConnectionprofile(Character connectionprofile) {
        this.connectionprofile = connectionprofile;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getUserpin() {
        return this.userpin;
    }
    
    public void setUserpin(String userpin) {
        this.userpin = userpin;
    }
    public char getIsinpayroll() {
        return this.isinpayroll;
    }
    
    public void setIsinpayroll(char isinpayroll) {
        this.isinpayroll = isinpayroll;
    }
    public Set getAdWorkflowprocessors() {
        return this.adWorkflowprocessors;
    }
    
    public void setAdWorkflowprocessors(Set adWorkflowprocessors) {
        this.adWorkflowprocessors = adWorkflowprocessors;
    }
    public Set getAdRoles() {
        return this.adRoles;
    }
    
    public void setAdRoles(Set adRoles) {
        this.adRoles = adRoles;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }
    public Set getAdUserOrgaccesses() {
        return this.adUserOrgaccesses;
    }
    
    public void setAdUserOrgaccesses(Set adUserOrgaccesses) {
        this.adUserOrgaccesses = adUserOrgaccesses;
    }
    public Set getAdUserRoleses() {
        return this.adUserRoleses;
    }
    
    public void setAdUserRoleses(Set adUserRoleses) {
        this.adUserRoleses = adUserRoleses;
    }
    public Set getCSalesregions() {
        return this.CSalesregions;
    }
    
    public void setCSalesregions(Set CSalesregions) {
        this.CSalesregions = CSalesregions;
    }
    public Set getAdUsers() {
        return this.adUsers;
    }
    
    public void setAdUsers(Set adUsers) {
        this.adUsers = adUsers;
    }
    public Set getAdWfResponsibles() {
        return this.adWfResponsibles;
    }
    
    public void setAdWfResponsibles(Set adWfResponsibles) {
        this.adWfResponsibles = adWfResponsibles;
    }
    public Set getSResources() {
        return this.SResources;
    }
    
    public void setSResources(Set SResources) {
        this.SResources = SResources;
    }




}


