package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0



/**
 * AdUserOrgaccessId generated by hbm2java
 */
public class AdUserOrgaccessId  implements java.io.Serializable {


     private long adUserId;
     private long adOrgId;

    public AdUserOrgaccessId() {
    }

    public AdUserOrgaccessId(long adUserId, long adOrgId) {
       this.adUserId = adUserId;
       this.adOrgId = adOrgId;
    }
   
    public long getAdUserId() {
        return this.adUserId;
    }
    
    public void setAdUserId(long adUserId) {
        this.adUserId = adUserId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }




}


