package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdValRule generated by hbm2java
 */
public class AdValRule  implements java.io.Serializable {


     private long adValRuleId;
     private AdClient adClient;
     private AdOrg adOrg;
     private AdEntitytype adEntitytype;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private Character type;
     private String code;
     private Set adTables = new HashSet(0);
     private Set adColumns = new HashSet(0);

    public AdValRule() {
    }

	
    public AdValRule(long adValRuleId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name) {
        this.adValRuleId = adValRuleId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
    }
    public AdValRule(long adValRuleId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, Character type, String code, Set adTables, Set adColumns) {
       this.adValRuleId = adValRuleId;
       this.adClient = adClient;
       this.adOrg = adOrg;
       this.adEntitytype = adEntitytype;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.type = type;
       this.code = code;
       this.adTables = adTables;
       this.adColumns = adColumns;
    }
   
    public long getAdValRuleId() {
        return this.adValRuleId;
    }
    
    public void setAdValRuleId(long adValRuleId) {
        this.adValRuleId = adValRuleId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Character getType() {
        return this.type;
    }
    
    public void setType(Character type) {
        this.type = type;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getAdTables() {
        return this.adTables;
    }
    
    public void setAdTables(Set adTables) {
        this.adTables = adTables;
    }
    public Set getAdColumns() {
        return this.adColumns;
    }
    
    public void setAdColumns(Set adColumns) {
        this.adColumns = adColumns;
    }




}


