package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdWfNode generated by hbm2java
 */
public class AdWfNode  implements java.io.Serializable {


     private long adWfNodeId;
     private CBpartner CBpartner;
     private AdWfResponsible adWfResponsible;
     private SResource SResource;
     private AdWorkflow adWorkflowByAdWorkflowId;
     private AdProcess adProcess;
     private AdForm adForm;
     private AdOrg adOrg;
     private AdEntitytype adEntitytype;
     private AdTask adTask;
     private AdWorkflow adWorkflowByWorkflowId;
     private AdClient adClient;
     private AdWindow adWindow;
     private AdImage adImage;
     private AdColumn adColumn;
     private AdWfBlock adWfBlock;
     private RMailtext RMailtext;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private char iscentrallymaintained;
     private char action;
     private long xposition;
     private long yposition;
     private Character subflowexecution;
     private Character startmode;
     private Character finishmode;
     private long limit;
     private Long priority;
     private long duration;
     private BigDecimal cost;
     private Long workingtime;
     private long waitingtime;
     private char joinelement;
     private char splitelement;
     private Long waittime;
     private String attributename;
     private String attributevalue;
     private String docaction;
     private String value;
     private Character dynpriorityunit;
     private BigDecimal dynprioritychange;
     private Character emailrecipient;
     private String email;
     private Date validto;
     private Character ismilestone;
     private Character issubcontracting;
     private BigDecimal unitscycles;
     private Long movingtime;
     private Long overlapunits;
     private Long queuingtime;
     private Long setuptime;
     private Date validfrom;
     private Long yield;
     private Set adWorkflows = new HashSet(0);

    public AdWfNode() {
    }

	
    public AdWfNode(long adWfNodeId, AdWorkflow adWorkflowByAdWorkflowId, AdOrg adOrg, AdEntitytype adEntitytype, AdClient adClient, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char iscentrallymaintained, char action, long xposition, long yposition, long limit, long duration, BigDecimal cost, long waitingtime, char joinelement, char splitelement, String value) {
        this.adWfNodeId = adWfNodeId;
        this.adWorkflowByAdWorkflowId = adWorkflowByAdWorkflowId;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.adClient = adClient;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.iscentrallymaintained = iscentrallymaintained;
        this.action = action;
        this.xposition = xposition;
        this.yposition = yposition;
        this.limit = limit;
        this.duration = duration;
        this.cost = cost;
        this.waitingtime = waitingtime;
        this.joinelement = joinelement;
        this.splitelement = splitelement;
        this.value = value;
    }
    public AdWfNode(long adWfNodeId, CBpartner CBpartner, AdWfResponsible adWfResponsible, SResource SResource, AdWorkflow adWorkflowByAdWorkflowId, AdProcess adProcess, AdForm adForm, AdOrg adOrg, AdEntitytype adEntitytype, AdTask adTask, AdWorkflow adWorkflowByWorkflowId, AdClient adClient, AdWindow adWindow, AdImage adImage, AdColumn adColumn, AdWfBlock adWfBlock, RMailtext RMailtext, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, char iscentrallymaintained, char action, long xposition, long yposition, Character subflowexecution, Character startmode, Character finishmode, long limit, Long priority, long duration, BigDecimal cost, Long workingtime, long waitingtime, char joinelement, char splitelement, Long waittime, String attributename, String attributevalue, String docaction, String value, Character dynpriorityunit, BigDecimal dynprioritychange, Character emailrecipient, String email, Date validto, Character ismilestone, Character issubcontracting, BigDecimal unitscycles, Long movingtime, Long overlapunits, Long queuingtime, Long setuptime, Date validfrom, Long yield, Set adWorkflows) {
       this.adWfNodeId = adWfNodeId;
       this.CBpartner = CBpartner;
       this.adWfResponsible = adWfResponsible;
       this.SResource = SResource;
       this.adWorkflowByAdWorkflowId = adWorkflowByAdWorkflowId;
       this.adProcess = adProcess;
       this.adForm = adForm;
       this.adOrg = adOrg;
       this.adEntitytype = adEntitytype;
       this.adTask = adTask;
       this.adWorkflowByWorkflowId = adWorkflowByWorkflowId;
       this.adClient = adClient;
       this.adWindow = adWindow;
       this.adImage = adImage;
       this.adColumn = adColumn;
       this.adWfBlock = adWfBlock;
       this.RMailtext = RMailtext;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.iscentrallymaintained = iscentrallymaintained;
       this.action = action;
       this.xposition = xposition;
       this.yposition = yposition;
       this.subflowexecution = subflowexecution;
       this.startmode = startmode;
       this.finishmode = finishmode;
       this.limit = limit;
       this.priority = priority;
       this.duration = duration;
       this.cost = cost;
       this.workingtime = workingtime;
       this.waitingtime = waitingtime;
       this.joinelement = joinelement;
       this.splitelement = splitelement;
       this.waittime = waittime;
       this.attributename = attributename;
       this.attributevalue = attributevalue;
       this.docaction = docaction;
       this.value = value;
       this.dynpriorityunit = dynpriorityunit;
       this.dynprioritychange = dynprioritychange;
       this.emailrecipient = emailrecipient;
       this.email = email;
       this.validto = validto;
       this.ismilestone = ismilestone;
       this.issubcontracting = issubcontracting;
       this.unitscycles = unitscycles;
       this.movingtime = movingtime;
       this.overlapunits = overlapunits;
       this.queuingtime = queuingtime;
       this.setuptime = setuptime;
       this.validfrom = validfrom;
       this.yield = yield;
       this.adWorkflows = adWorkflows;
    }
   
    public long getAdWfNodeId() {
        return this.adWfNodeId;
    }
    
    public void setAdWfNodeId(long adWfNodeId) {
        this.adWfNodeId = adWfNodeId;
    }
    public CBpartner getCBpartner() {
        return this.CBpartner;
    }
    
    public void setCBpartner(CBpartner CBpartner) {
        this.CBpartner = CBpartner;
    }
    public AdWfResponsible getAdWfResponsible() {
        return this.adWfResponsible;
    }
    
    public void setAdWfResponsible(AdWfResponsible adWfResponsible) {
        this.adWfResponsible = adWfResponsible;
    }
    public SResource getSResource() {
        return this.SResource;
    }
    
    public void setSResource(SResource SResource) {
        this.SResource = SResource;
    }
    public AdWorkflow getAdWorkflowByAdWorkflowId() {
        return this.adWorkflowByAdWorkflowId;
    }
    
    public void setAdWorkflowByAdWorkflowId(AdWorkflow adWorkflowByAdWorkflowId) {
        this.adWorkflowByAdWorkflowId = adWorkflowByAdWorkflowId;
    }
    public AdProcess getAdProcess() {
        return this.adProcess;
    }
    
    public void setAdProcess(AdProcess adProcess) {
        this.adProcess = adProcess;
    }
    public AdForm getAdForm() {
        return this.adForm;
    }
    
    public void setAdForm(AdForm adForm) {
        this.adForm = adForm;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public AdTask getAdTask() {
        return this.adTask;
    }
    
    public void setAdTask(AdTask adTask) {
        this.adTask = adTask;
    }
    public AdWorkflow getAdWorkflowByWorkflowId() {
        return this.adWorkflowByWorkflowId;
    }
    
    public void setAdWorkflowByWorkflowId(AdWorkflow adWorkflowByWorkflowId) {
        this.adWorkflowByWorkflowId = adWorkflowByWorkflowId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdWindow getAdWindow() {
        return this.adWindow;
    }
    
    public void setAdWindow(AdWindow adWindow) {
        this.adWindow = adWindow;
    }
    public AdImage getAdImage() {
        return this.adImage;
    }
    
    public void setAdImage(AdImage adImage) {
        this.adImage = adImage;
    }
    public AdColumn getAdColumn() {
        return this.adColumn;
    }
    
    public void setAdColumn(AdColumn adColumn) {
        this.adColumn = adColumn;
    }
    public AdWfBlock getAdWfBlock() {
        return this.adWfBlock;
    }
    
    public void setAdWfBlock(AdWfBlock adWfBlock) {
        this.adWfBlock = adWfBlock;
    }
    public RMailtext getRMailtext() {
        return this.RMailtext;
    }
    
    public void setRMailtext(RMailtext RMailtext) {
        this.RMailtext = RMailtext;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public char getIscentrallymaintained() {
        return this.iscentrallymaintained;
    }
    
    public void setIscentrallymaintained(char iscentrallymaintained) {
        this.iscentrallymaintained = iscentrallymaintained;
    }
    public char getAction() {
        return this.action;
    }
    
    public void setAction(char action) {
        this.action = action;
    }
    public long getXposition() {
        return this.xposition;
    }
    
    public void setXposition(long xposition) {
        this.xposition = xposition;
    }
    public long getYposition() {
        return this.yposition;
    }
    
    public void setYposition(long yposition) {
        this.yposition = yposition;
    }
    public Character getSubflowexecution() {
        return this.subflowexecution;
    }
    
    public void setSubflowexecution(Character subflowexecution) {
        this.subflowexecution = subflowexecution;
    }
    public Character getStartmode() {
        return this.startmode;
    }
    
    public void setStartmode(Character startmode) {
        this.startmode = startmode;
    }
    public Character getFinishmode() {
        return this.finishmode;
    }
    
    public void setFinishmode(Character finishmode) {
        this.finishmode = finishmode;
    }
    public long getLimit() {
        return this.limit;
    }
    
    public void setLimit(long limit) {
        this.limit = limit;
    }
    public Long getPriority() {
        return this.priority;
    }
    
    public void setPriority(Long priority) {
        this.priority = priority;
    }
    public long getDuration() {
        return this.duration;
    }
    
    public void setDuration(long duration) {
        this.duration = duration;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public Long getWorkingtime() {
        return this.workingtime;
    }
    
    public void setWorkingtime(Long workingtime) {
        this.workingtime = workingtime;
    }
    public long getWaitingtime() {
        return this.waitingtime;
    }
    
    public void setWaitingtime(long waitingtime) {
        this.waitingtime = waitingtime;
    }
    public char getJoinelement() {
        return this.joinelement;
    }
    
    public void setJoinelement(char joinelement) {
        this.joinelement = joinelement;
    }
    public char getSplitelement() {
        return this.splitelement;
    }
    
    public void setSplitelement(char splitelement) {
        this.splitelement = splitelement;
    }
    public Long getWaittime() {
        return this.waittime;
    }
    
    public void setWaittime(Long waittime) {
        this.waittime = waittime;
    }
    public String getAttributename() {
        return this.attributename;
    }
    
    public void setAttributename(String attributename) {
        this.attributename = attributename;
    }
    public String getAttributevalue() {
        return this.attributevalue;
    }
    
    public void setAttributevalue(String attributevalue) {
        this.attributevalue = attributevalue;
    }
    public String getDocaction() {
        return this.docaction;
    }
    
    public void setDocaction(String docaction) {
        this.docaction = docaction;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Character getDynpriorityunit() {
        return this.dynpriorityunit;
    }
    
    public void setDynpriorityunit(Character dynpriorityunit) {
        this.dynpriorityunit = dynpriorityunit;
    }
    public BigDecimal getDynprioritychange() {
        return this.dynprioritychange;
    }
    
    public void setDynprioritychange(BigDecimal dynprioritychange) {
        this.dynprioritychange = dynprioritychange;
    }
    public Character getEmailrecipient() {
        return this.emailrecipient;
    }
    
    public void setEmailrecipient(Character emailrecipient) {
        this.emailrecipient = emailrecipient;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }
    public Character getIsmilestone() {
        return this.ismilestone;
    }
    
    public void setIsmilestone(Character ismilestone) {
        this.ismilestone = ismilestone;
    }
    public Character getIssubcontracting() {
        return this.issubcontracting;
    }
    
    public void setIssubcontracting(Character issubcontracting) {
        this.issubcontracting = issubcontracting;
    }
    public BigDecimal getUnitscycles() {
        return this.unitscycles;
    }
    
    public void setUnitscycles(BigDecimal unitscycles) {
        this.unitscycles = unitscycles;
    }
    public Long getMovingtime() {
        return this.movingtime;
    }
    
    public void setMovingtime(Long movingtime) {
        this.movingtime = movingtime;
    }
    public Long getOverlapunits() {
        return this.overlapunits;
    }
    
    public void setOverlapunits(Long overlapunits) {
        this.overlapunits = overlapunits;
    }
    public Long getQueuingtime() {
        return this.queuingtime;
    }
    
    public void setQueuingtime(Long queuingtime) {
        this.queuingtime = queuingtime;
    }
    public Long getSetuptime() {
        return this.setuptime;
    }
    
    public void setSetuptime(Long setuptime) {
        this.setuptime = setuptime;
    }
    public Date getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }
    public Long getYield() {
        return this.yield;
    }
    
    public void setYield(Long yield) {
        this.yield = yield;
    }
    public Set getAdWorkflows() {
        return this.adWorkflows;
    }
    
    public void setAdWorkflows(Set adWorkflows) {
        this.adWorkflows = adWorkflows;
    }




}


