package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdWindow generated by hbm2java
 */
public class AdWindow  implements java.io.Serializable {


     private long adWindowId;
     private AdColor adColor;
     private AdClient adClient;
     private AdImage adImage;
     private AdOrg adOrg;
     private AdEntitytype adEntitytype;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private Character windowtype;
     private char issotrx;
     private Character processing;
     private char isdefault;
     private Long winheight;
     private Long winwidth;
     private char isbetafunctionality;
     private Set adTablesForPoWindowId = new HashSet(0);
     private Set adWfNodes = new HashSet(0);
     private Set adMenus = new HashSet(0);
     private Set adTablesForAdWindowId = new HashSet(0);

    public AdWindow() {
    }

	
    public AdWindow(long adWindowId, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char issotrx, char isdefault, char isbetafunctionality) {
        this.adWindowId = adWindowId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.issotrx = issotrx;
        this.isdefault = isdefault;
        this.isbetafunctionality = isbetafunctionality;
    }
    public AdWindow(long adWindowId, AdColor adColor, AdClient adClient, AdImage adImage, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, Character windowtype, char issotrx, Character processing, char isdefault, Long winheight, Long winwidth, char isbetafunctionality, Set adTablesForPoWindowId, Set adWfNodes, Set adMenus, Set adTablesForAdWindowId) {
       this.adWindowId = adWindowId;
       this.adColor = adColor;
       this.adClient = adClient;
       this.adImage = adImage;
       this.adOrg = adOrg;
       this.adEntitytype = adEntitytype;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.windowtype = windowtype;
       this.issotrx = issotrx;
       this.processing = processing;
       this.isdefault = isdefault;
       this.winheight = winheight;
       this.winwidth = winwidth;
       this.isbetafunctionality = isbetafunctionality;
       this.adTablesForPoWindowId = adTablesForPoWindowId;
       this.adWfNodes = adWfNodes;
       this.adMenus = adMenus;
       this.adTablesForAdWindowId = adTablesForAdWindowId;
    }
   
    public long getAdWindowId() {
        return this.adWindowId;
    }
    
    public void setAdWindowId(long adWindowId) {
        this.adWindowId = adWindowId;
    }
    public AdColor getAdColor() {
        return this.adColor;
    }
    
    public void setAdColor(AdColor adColor) {
        this.adColor = adColor;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdImage getAdImage() {
        return this.adImage;
    }
    
    public void setAdImage(AdImage adImage) {
        this.adImage = adImage;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public Character getWindowtype() {
        return this.windowtype;
    }
    
    public void setWindowtype(Character windowtype) {
        this.windowtype = windowtype;
    }
    public char getIssotrx() {
        return this.issotrx;
    }
    
    public void setIssotrx(char issotrx) {
        this.issotrx = issotrx;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Long getWinheight() {
        return this.winheight;
    }
    
    public void setWinheight(Long winheight) {
        this.winheight = winheight;
    }
    public Long getWinwidth() {
        return this.winwidth;
    }
    
    public void setWinwidth(Long winwidth) {
        this.winwidth = winwidth;
    }
    public char getIsbetafunctionality() {
        return this.isbetafunctionality;
    }
    
    public void setIsbetafunctionality(char isbetafunctionality) {
        this.isbetafunctionality = isbetafunctionality;
    }
    public Set getAdTablesForPoWindowId() {
        return this.adTablesForPoWindowId;
    }
    
    public void setAdTablesForPoWindowId(Set adTablesForPoWindowId) {
        this.adTablesForPoWindowId = adTablesForPoWindowId;
    }
    public Set getAdWfNodes() {
        return this.adWfNodes;
    }
    
    public void setAdWfNodes(Set adWfNodes) {
        this.adWfNodes = adWfNodes;
    }
    public Set getAdMenus() {
        return this.adMenus;
    }
    
    public void setAdMenus(Set adMenus) {
        this.adMenus = adMenus;
    }
    public Set getAdTablesForAdWindowId() {
        return this.adTablesForAdWindowId;
    }
    
    public void setAdTablesForAdWindowId(Set adTablesForAdWindowId) {
        this.adTablesForAdWindowId = adTablesForAdWindowId;
    }




}


