package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdWorkflow generated by hbm2java
 */
public class AdWorkflow  implements java.io.Serializable {


     private long adWorkflowId;
     private long version;
     private AdTable adTable;
     private AdWfResponsible adWfResponsible;
     private AdClient adClient;
     private SResource SResource;
     private AdWfNode adWfNode;
     private AdOrg adOrg;
     private AdWorkflowprocessor adWorkflowprocessor;
     private AdEntitytype adEntitytype;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private char accesslevel;
     private Character durationunit;
     private String author;
     private Date validfrom;
     private Date validto;
     private Long priority;
     private Long limit;
     private long duration;
     private BigDecimal cost;
     private long workingtime;
     private long waitingtime;
     private char publishstatus;
     private String value;
     private char isdefault;
     private Character validateworkflow;
     private char workflowtype;
     private String docvaluelogic;
     private char isvalid;
     private Long setuptime;
     private Long movingtime;
     private String processtype;
     private String documentno;
     private BigDecimal qtybatchsize;
     private Long queuingtime;
     private char isbetafunctionality;
     private Long yield;
     private BigDecimal unitscycles;
     private BigDecimal overlapunits;
     private Set adProcesses = new HashSet(0);
     private Set adWfNodesForWorkflowId = new HashSet(0);
     private Set adWfBlocks = new HashSet(0);
     private Set adWfNodesForAdWorkflowId = new HashSet(0);
     private Set adMenus = new HashSet(0);

    public AdWorkflow() {
    }

	
    public AdWorkflow(long adWorkflowId, long version, AdClient adClient, AdOrg adOrg, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char accesslevel, String author, long duration, BigDecimal cost, long workingtime, long waitingtime, char publishstatus, String value, char isdefault, char workflowtype, char isvalid, char isbetafunctionality) {
        this.adWorkflowId = adWorkflowId;
        this.version = version;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.adEntitytype = adEntitytype;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.accesslevel = accesslevel;
        this.author = author;
        this.duration = duration;
        this.cost = cost;
        this.workingtime = workingtime;
        this.waitingtime = waitingtime;
        this.publishstatus = publishstatus;
        this.value = value;
        this.isdefault = isdefault;
        this.workflowtype = workflowtype;
        this.isvalid = isvalid;
        this.isbetafunctionality = isbetafunctionality;
    }
    public AdWorkflow(long adWorkflowId, long version, AdTable adTable, AdWfResponsible adWfResponsible, AdClient adClient, SResource SResource, AdWfNode adWfNode, AdOrg adOrg, AdWorkflowprocessor adWorkflowprocessor, AdEntitytype adEntitytype, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, char accesslevel, Character durationunit, String author, Date validfrom, Date validto, Long priority, Long limit, long duration, BigDecimal cost, long workingtime, long waitingtime, char publishstatus, String value, char isdefault, Character validateworkflow, char workflowtype, String docvaluelogic, char isvalid, Long setuptime, Long movingtime, String processtype, String documentno, BigDecimal qtybatchsize, Long queuingtime, char isbetafunctionality, Long yield, BigDecimal unitscycles, BigDecimal overlapunits, Set adProcesses, Set adWfNodesForWorkflowId, Set adWfBlocks, Set adWfNodesForAdWorkflowId, Set adMenus) {
       this.adWorkflowId = adWorkflowId;
       this.version = version;
       this.adTable = adTable;
       this.adWfResponsible = adWfResponsible;
       this.adClient = adClient;
       this.SResource = SResource;
       this.adWfNode = adWfNode;
       this.adOrg = adOrg;
       this.adWorkflowprocessor = adWorkflowprocessor;
       this.adEntitytype = adEntitytype;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.accesslevel = accesslevel;
       this.durationunit = durationunit;
       this.author = author;
       this.validfrom = validfrom;
       this.validto = validto;
       this.priority = priority;
       this.limit = limit;
       this.duration = duration;
       this.cost = cost;
       this.workingtime = workingtime;
       this.waitingtime = waitingtime;
       this.publishstatus = publishstatus;
       this.value = value;
       this.isdefault = isdefault;
       this.validateworkflow = validateworkflow;
       this.workflowtype = workflowtype;
       this.docvaluelogic = docvaluelogic;
       this.isvalid = isvalid;
       this.setuptime = setuptime;
       this.movingtime = movingtime;
       this.processtype = processtype;
       this.documentno = documentno;
       this.qtybatchsize = qtybatchsize;
       this.queuingtime = queuingtime;
       this.isbetafunctionality = isbetafunctionality;
       this.yield = yield;
       this.unitscycles = unitscycles;
       this.overlapunits = overlapunits;
       this.adProcesses = adProcesses;
       this.adWfNodesForWorkflowId = adWfNodesForWorkflowId;
       this.adWfBlocks = adWfBlocks;
       this.adWfNodesForAdWorkflowId = adWfNodesForAdWorkflowId;
       this.adMenus = adMenus;
    }
   
    public long getAdWorkflowId() {
        return this.adWorkflowId;
    }
    
    public void setAdWorkflowId(long adWorkflowId) {
        this.adWorkflowId = adWorkflowId;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public AdTable getAdTable() {
        return this.adTable;
    }
    
    public void setAdTable(AdTable adTable) {
        this.adTable = adTable;
    }
    public AdWfResponsible getAdWfResponsible() {
        return this.adWfResponsible;
    }
    
    public void setAdWfResponsible(AdWfResponsible adWfResponsible) {
        this.adWfResponsible = adWfResponsible;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public SResource getSResource() {
        return this.SResource;
    }
    
    public void setSResource(SResource SResource) {
        this.SResource = SResource;
    }
    public AdWfNode getAdWfNode() {
        return this.adWfNode;
    }
    
    public void setAdWfNode(AdWfNode adWfNode) {
        this.adWfNode = adWfNode;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public AdWorkflowprocessor getAdWorkflowprocessor() {
        return this.adWorkflowprocessor;
    }
    
    public void setAdWorkflowprocessor(AdWorkflowprocessor adWorkflowprocessor) {
        this.adWorkflowprocessor = adWorkflowprocessor;
    }
    public AdEntitytype getAdEntitytype() {
        return this.adEntitytype;
    }
    
    public void setAdEntitytype(AdEntitytype adEntitytype) {
        this.adEntitytype = adEntitytype;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public char getAccesslevel() {
        return this.accesslevel;
    }
    
    public void setAccesslevel(char accesslevel) {
        this.accesslevel = accesslevel;
    }
    public Character getDurationunit() {
        return this.durationunit;
    }
    
    public void setDurationunit(Character durationunit) {
        this.durationunit = durationunit;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }
    public Long getPriority() {
        return this.priority;
    }
    
    public void setPriority(Long priority) {
        this.priority = priority;
    }
    public Long getLimit() {
        return this.limit;
    }
    
    public void setLimit(Long limit) {
        this.limit = limit;
    }
    public long getDuration() {
        return this.duration;
    }
    
    public void setDuration(long duration) {
        this.duration = duration;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public long getWorkingtime() {
        return this.workingtime;
    }
    
    public void setWorkingtime(long workingtime) {
        this.workingtime = workingtime;
    }
    public long getWaitingtime() {
        return this.waitingtime;
    }
    
    public void setWaitingtime(long waitingtime) {
        this.waitingtime = waitingtime;
    }
    public char getPublishstatus() {
        return this.publishstatus;
    }
    
    public void setPublishstatus(char publishstatus) {
        this.publishstatus = publishstatus;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Character getValidateworkflow() {
        return this.validateworkflow;
    }
    
    public void setValidateworkflow(Character validateworkflow) {
        this.validateworkflow = validateworkflow;
    }
    public char getWorkflowtype() {
        return this.workflowtype;
    }
    
    public void setWorkflowtype(char workflowtype) {
        this.workflowtype = workflowtype;
    }
    public String getDocvaluelogic() {
        return this.docvaluelogic;
    }
    
    public void setDocvaluelogic(String docvaluelogic) {
        this.docvaluelogic = docvaluelogic;
    }
    public char getIsvalid() {
        return this.isvalid;
    }
    
    public void setIsvalid(char isvalid) {
        this.isvalid = isvalid;
    }
    public Long getSetuptime() {
        return this.setuptime;
    }
    
    public void setSetuptime(Long setuptime) {
        this.setuptime = setuptime;
    }
    public Long getMovingtime() {
        return this.movingtime;
    }
    
    public void setMovingtime(Long movingtime) {
        this.movingtime = movingtime;
    }
    public String getProcesstype() {
        return this.processtype;
    }
    
    public void setProcesstype(String processtype) {
        this.processtype = processtype;
    }
    public String getDocumentno() {
        return this.documentno;
    }
    
    public void setDocumentno(String documentno) {
        this.documentno = documentno;
    }
    public BigDecimal getQtybatchsize() {
        return this.qtybatchsize;
    }
    
    public void setQtybatchsize(BigDecimal qtybatchsize) {
        this.qtybatchsize = qtybatchsize;
    }
    public Long getQueuingtime() {
        return this.queuingtime;
    }
    
    public void setQueuingtime(Long queuingtime) {
        this.queuingtime = queuingtime;
    }
    public char getIsbetafunctionality() {
        return this.isbetafunctionality;
    }
    
    public void setIsbetafunctionality(char isbetafunctionality) {
        this.isbetafunctionality = isbetafunctionality;
    }
    public Long getYield() {
        return this.yield;
    }
    
    public void setYield(Long yield) {
        this.yield = yield;
    }
    public BigDecimal getUnitscycles() {
        return this.unitscycles;
    }
    
    public void setUnitscycles(BigDecimal unitscycles) {
        this.unitscycles = unitscycles;
    }
    public BigDecimal getOverlapunits() {
        return this.overlapunits;
    }
    
    public void setOverlapunits(BigDecimal overlapunits) {
        this.overlapunits = overlapunits;
    }
    public Set getAdProcesses() {
        return this.adProcesses;
    }
    
    public void setAdProcesses(Set adProcesses) {
        this.adProcesses = adProcesses;
    }
    public Set getAdWfNodesForWorkflowId() {
        return this.adWfNodesForWorkflowId;
    }
    
    public void setAdWfNodesForWorkflowId(Set adWfNodesForWorkflowId) {
        this.adWfNodesForWorkflowId = adWfNodesForWorkflowId;
    }
    public Set getAdWfBlocks() {
        return this.adWfBlocks;
    }
    
    public void setAdWfBlocks(Set adWfBlocks) {
        this.adWfBlocks = adWfBlocks;
    }
    public Set getAdWfNodesForAdWorkflowId() {
        return this.adWfNodesForAdWorkflowId;
    }
    
    public void setAdWfNodesForAdWorkflowId(Set adWfNodesForAdWorkflowId) {
        this.adWfNodesForAdWorkflowId = adWfNodesForAdWorkflowId;
    }
    public Set getAdMenus() {
        return this.adMenus;
    }
    
    public void setAdMenus(Set adMenus) {
        this.adMenus = adMenus;
    }




}


