package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CBpartner generated by hbm2java
 */
public class CBpartner  implements java.io.Serializable {


     private long CBpartnerId;
     private AdPrintformat adPrintformat;
     private CBpartner CBpartner;
     private CGreeting CGreeting;
     private AdImage adImage;
     private AdOrg adOrgByAdOrgbpId;
     private AdUser adUser;
     private AdOrg adOrgByAdOrgId;
     private MDiscountschema MDiscountschemaByMDiscountschemaId;
     private CBpGroup CBpGroup;
     private CDunning CDunning;
     private CTaxgroup CTaxgroup;
     private MPricelist MPricelistByMPricelistId;
     private CPaymentterm CPaymenttermByPoPaymenttermId;
     private AdClient adClient;
     private CPaymentterm CPaymenttermByCPaymenttermId;
     private CInvoiceschedule CInvoiceschedule;
     private MPricelist MPricelistByPoPricelistId;
     private AdLanguage adLanguage;
     private MDiscountschema MDiscountschemaByPoDiscountschemaId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String value;
     private String name;
     private String name2;
     private String description;
     private char issummary;
     private char isonetime;
     private char isprospect;
     private char isvendor;
     private char iscustomer;
     private char isemployee;
     private char issalesrep;
     private String referenceno;
     private String duns;
     private String url;
     private String taxid;
     private Character istaxexempt;
     private Character rating;
     private Long salesvolume;
     private Long numberemployees;
     private String naics;
     private Date firstsale;
     private BigDecimal acqusitioncost;
     private BigDecimal potentiallifetimevalue;
     private BigDecimal actuallifetimevalue;
     private Long shareofcustomer;
     private Character paymentrule;
     private BigDecimal soCreditlimit;
     private BigDecimal soCreditused;
     private Character isdiscountprinted;
     private String soDescription;
     private String poreference;
     private Character paymentrulepo;
     private Long documentcopies;
     private Character invoicerule;
     private Character deliveryrule;
     private Character freightcostrule;
     private Character deliveryviarule;
     private char sendemail;
     private Character socreditstatus;
     private Long shelflifeminpct;
     private BigDecimal flatdiscount;
     private BigDecimal totalopenbalance;
     private Date dunninggrace;
     private char ispotaxexempt;
     private Character ismanufacturer;
     private Set adUsers = new HashSet(0);
     private Set CBpartnerLocations = new HashSet(0);
     private Set CBpartners = new HashSet(0);
     private Set adWfNodes = new HashSet(0);

    public CBpartner() {
    }

	
    public CBpartner(long CBpartnerId, AdOrg adOrgByAdOrgId, CBpGroup CBpGroup, AdClient adClient, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name, char issummary, char isonetime, char isprospect, char isvendor, char iscustomer, char isemployee, char issalesrep, char sendemail, char ispotaxexempt) {
        this.CBpartnerId = CBpartnerId;
        this.adOrgByAdOrgId = adOrgByAdOrgId;
        this.CBpGroup = CBpGroup;
        this.adClient = adClient;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.value = value;
        this.name = name;
        this.issummary = issummary;
        this.isonetime = isonetime;
        this.isprospect = isprospect;
        this.isvendor = isvendor;
        this.iscustomer = iscustomer;
        this.isemployee = isemployee;
        this.issalesrep = issalesrep;
        this.sendemail = sendemail;
        this.ispotaxexempt = ispotaxexempt;
    }
    public CBpartner(long CBpartnerId, AdPrintformat adPrintformat, CBpartner CBpartner, CGreeting CGreeting, AdImage adImage, AdOrg adOrgByAdOrgbpId, AdUser adUser, AdOrg adOrgByAdOrgId, MDiscountschema MDiscountschemaByMDiscountschemaId, CBpGroup CBpGroup, CDunning CDunning, CTaxgroup CTaxgroup, MPricelist MPricelistByMPricelistId, CPaymentterm CPaymenttermByPoPaymenttermId, AdClient adClient, CPaymentterm CPaymenttermByCPaymenttermId, CInvoiceschedule CInvoiceschedule, MPricelist MPricelistByPoPricelistId, AdLanguage adLanguage, MDiscountschema MDiscountschemaByPoDiscountschemaId, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name, String name2, String description, char issummary, char isonetime, char isprospect, char isvendor, char iscustomer, char isemployee, char issalesrep, String referenceno, String duns, String url, String taxid, Character istaxexempt, Character rating, Long salesvolume, Long numberemployees, String naics, Date firstsale, BigDecimal acqusitioncost, BigDecimal potentiallifetimevalue, BigDecimal actuallifetimevalue, Long shareofcustomer, Character paymentrule, BigDecimal soCreditlimit, BigDecimal soCreditused, Character isdiscountprinted, String soDescription, String poreference, Character paymentrulepo, Long documentcopies, Character invoicerule, Character deliveryrule, Character freightcostrule, Character deliveryviarule, char sendemail, Character socreditstatus, Long shelflifeminpct, BigDecimal flatdiscount, BigDecimal totalopenbalance, Date dunninggrace, char ispotaxexempt, Character ismanufacturer, Set adUsers, Set CBpartnerLocations, Set CBpartners, Set adWfNodes) {
       this.CBpartnerId = CBpartnerId;
       this.adPrintformat = adPrintformat;
       this.CBpartner = CBpartner;
       this.CGreeting = CGreeting;
       this.adImage = adImage;
       this.adOrgByAdOrgbpId = adOrgByAdOrgbpId;
       this.adUser = adUser;
       this.adOrgByAdOrgId = adOrgByAdOrgId;
       this.MDiscountschemaByMDiscountschemaId = MDiscountschemaByMDiscountschemaId;
       this.CBpGroup = CBpGroup;
       this.CDunning = CDunning;
       this.CTaxgroup = CTaxgroup;
       this.MPricelistByMPricelistId = MPricelistByMPricelistId;
       this.CPaymenttermByPoPaymenttermId = CPaymenttermByPoPaymenttermId;
       this.adClient = adClient;
       this.CPaymenttermByCPaymenttermId = CPaymenttermByCPaymenttermId;
       this.CInvoiceschedule = CInvoiceschedule;
       this.MPricelistByPoPricelistId = MPricelistByPoPricelistId;
       this.adLanguage = adLanguage;
       this.MDiscountschemaByPoDiscountschemaId = MDiscountschemaByPoDiscountschemaId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.value = value;
       this.name = name;
       this.name2 = name2;
       this.description = description;
       this.issummary = issummary;
       this.isonetime = isonetime;
       this.isprospect = isprospect;
       this.isvendor = isvendor;
       this.iscustomer = iscustomer;
       this.isemployee = isemployee;
       this.issalesrep = issalesrep;
       this.referenceno = referenceno;
       this.duns = duns;
       this.url = url;
       this.taxid = taxid;
       this.istaxexempt = istaxexempt;
       this.rating = rating;
       this.salesvolume = salesvolume;
       this.numberemployees = numberemployees;
       this.naics = naics;
       this.firstsale = firstsale;
       this.acqusitioncost = acqusitioncost;
       this.potentiallifetimevalue = potentiallifetimevalue;
       this.actuallifetimevalue = actuallifetimevalue;
       this.shareofcustomer = shareofcustomer;
       this.paymentrule = paymentrule;
       this.soCreditlimit = soCreditlimit;
       this.soCreditused = soCreditused;
       this.isdiscountprinted = isdiscountprinted;
       this.soDescription = soDescription;
       this.poreference = poreference;
       this.paymentrulepo = paymentrulepo;
       this.documentcopies = documentcopies;
       this.invoicerule = invoicerule;
       this.deliveryrule = deliveryrule;
       this.freightcostrule = freightcostrule;
       this.deliveryviarule = deliveryviarule;
       this.sendemail = sendemail;
       this.socreditstatus = socreditstatus;
       this.shelflifeminpct = shelflifeminpct;
       this.flatdiscount = flatdiscount;
       this.totalopenbalance = totalopenbalance;
       this.dunninggrace = dunninggrace;
       this.ispotaxexempt = ispotaxexempt;
       this.ismanufacturer = ismanufacturer;
       this.adUsers = adUsers;
       this.CBpartnerLocations = CBpartnerLocations;
       this.CBpartners = CBpartners;
       this.adWfNodes = adWfNodes;
    }
   
    public long getCBpartnerId() {
        return this.CBpartnerId;
    }
    
    public void setCBpartnerId(long CBpartnerId) {
        this.CBpartnerId = CBpartnerId;
    }
    public AdPrintformat getAdPrintformat() {
        return this.adPrintformat;
    }
    
    public void setAdPrintformat(AdPrintformat adPrintformat) {
        this.adPrintformat = adPrintformat;
    }
    public CBpartner getCBpartner() {
        return this.CBpartner;
    }
    
    public void setCBpartner(CBpartner CBpartner) {
        this.CBpartner = CBpartner;
    }
    public CGreeting getCGreeting() {
        return this.CGreeting;
    }
    
    public void setCGreeting(CGreeting CGreeting) {
        this.CGreeting = CGreeting;
    }
    public AdImage getAdImage() {
        return this.adImage;
    }
    
    public void setAdImage(AdImage adImage) {
        this.adImage = adImage;
    }
    public AdOrg getAdOrgByAdOrgbpId() {
        return this.adOrgByAdOrgbpId;
    }
    
    public void setAdOrgByAdOrgbpId(AdOrg adOrgByAdOrgbpId) {
        this.adOrgByAdOrgbpId = adOrgByAdOrgbpId;
    }
    public AdUser getAdUser() {
        return this.adUser;
    }
    
    public void setAdUser(AdUser adUser) {
        this.adUser = adUser;
    }
    public AdOrg getAdOrgByAdOrgId() {
        return this.adOrgByAdOrgId;
    }
    
    public void setAdOrgByAdOrgId(AdOrg adOrgByAdOrgId) {
        this.adOrgByAdOrgId = adOrgByAdOrgId;
    }
    public MDiscountschema getMDiscountschemaByMDiscountschemaId() {
        return this.MDiscountschemaByMDiscountschemaId;
    }
    
    public void setMDiscountschemaByMDiscountschemaId(MDiscountschema MDiscountschemaByMDiscountschemaId) {
        this.MDiscountschemaByMDiscountschemaId = MDiscountschemaByMDiscountschemaId;
    }
    public CBpGroup getCBpGroup() {
        return this.CBpGroup;
    }
    
    public void setCBpGroup(CBpGroup CBpGroup) {
        this.CBpGroup = CBpGroup;
    }
    public CDunning getCDunning() {
        return this.CDunning;
    }
    
    public void setCDunning(CDunning CDunning) {
        this.CDunning = CDunning;
    }
    public CTaxgroup getCTaxgroup() {
        return this.CTaxgroup;
    }
    
    public void setCTaxgroup(CTaxgroup CTaxgroup) {
        this.CTaxgroup = CTaxgroup;
    }
    public MPricelist getMPricelistByMPricelistId() {
        return this.MPricelistByMPricelistId;
    }
    
    public void setMPricelistByMPricelistId(MPricelist MPricelistByMPricelistId) {
        this.MPricelistByMPricelistId = MPricelistByMPricelistId;
    }
    public CPaymentterm getCPaymenttermByPoPaymenttermId() {
        return this.CPaymenttermByPoPaymenttermId;
    }
    
    public void setCPaymenttermByPoPaymenttermId(CPaymentterm CPaymenttermByPoPaymenttermId) {
        this.CPaymenttermByPoPaymenttermId = CPaymenttermByPoPaymenttermId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CPaymentterm getCPaymenttermByCPaymenttermId() {
        return this.CPaymenttermByCPaymenttermId;
    }
    
    public void setCPaymenttermByCPaymenttermId(CPaymentterm CPaymenttermByCPaymenttermId) {
        this.CPaymenttermByCPaymenttermId = CPaymenttermByCPaymenttermId;
    }
    public CInvoiceschedule getCInvoiceschedule() {
        return this.CInvoiceschedule;
    }
    
    public void setCInvoiceschedule(CInvoiceschedule CInvoiceschedule) {
        this.CInvoiceschedule = CInvoiceschedule;
    }
    public MPricelist getMPricelistByPoPricelistId() {
        return this.MPricelistByPoPricelistId;
    }
    
    public void setMPricelistByPoPricelistId(MPricelist MPricelistByPoPricelistId) {
        this.MPricelistByPoPricelistId = MPricelistByPoPricelistId;
    }
    public AdLanguage getAdLanguage() {
        return this.adLanguage;
    }
    
    public void setAdLanguage(AdLanguage adLanguage) {
        this.adLanguage = adLanguage;
    }
    public MDiscountschema getMDiscountschemaByPoDiscountschemaId() {
        return this.MDiscountschemaByPoDiscountschemaId;
    }
    
    public void setMDiscountschemaByPoDiscountschemaId(MDiscountschema MDiscountschemaByPoDiscountschemaId) {
        this.MDiscountschemaByPoDiscountschemaId = MDiscountschemaByPoDiscountschemaId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getIssummary() {
        return this.issummary;
    }
    
    public void setIssummary(char issummary) {
        this.issummary = issummary;
    }
    public char getIsonetime() {
        return this.isonetime;
    }
    
    public void setIsonetime(char isonetime) {
        this.isonetime = isonetime;
    }
    public char getIsprospect() {
        return this.isprospect;
    }
    
    public void setIsprospect(char isprospect) {
        this.isprospect = isprospect;
    }
    public char getIsvendor() {
        return this.isvendor;
    }
    
    public void setIsvendor(char isvendor) {
        this.isvendor = isvendor;
    }
    public char getIscustomer() {
        return this.iscustomer;
    }
    
    public void setIscustomer(char iscustomer) {
        this.iscustomer = iscustomer;
    }
    public char getIsemployee() {
        return this.isemployee;
    }
    
    public void setIsemployee(char isemployee) {
        this.isemployee = isemployee;
    }
    public char getIssalesrep() {
        return this.issalesrep;
    }
    
    public void setIssalesrep(char issalesrep) {
        this.issalesrep = issalesrep;
    }
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }
    public String getDuns() {
        return this.duns;
    }
    
    public void setDuns(String duns) {
        this.duns = duns;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getTaxid() {
        return this.taxid;
    }
    
    public void setTaxid(String taxid) {
        this.taxid = taxid;
    }
    public Character getIstaxexempt() {
        return this.istaxexempt;
    }
    
    public void setIstaxexempt(Character istaxexempt) {
        this.istaxexempt = istaxexempt;
    }
    public Character getRating() {
        return this.rating;
    }
    
    public void setRating(Character rating) {
        this.rating = rating;
    }
    public Long getSalesvolume() {
        return this.salesvolume;
    }
    
    public void setSalesvolume(Long salesvolume) {
        this.salesvolume = salesvolume;
    }
    public Long getNumberemployees() {
        return this.numberemployees;
    }
    
    public void setNumberemployees(Long numberemployees) {
        this.numberemployees = numberemployees;
    }
    public String getNaics() {
        return this.naics;
    }
    
    public void setNaics(String naics) {
        this.naics = naics;
    }
    public Date getFirstsale() {
        return this.firstsale;
    }
    
    public void setFirstsale(Date firstsale) {
        this.firstsale = firstsale;
    }
    public BigDecimal getAcqusitioncost() {
        return this.acqusitioncost;
    }
    
    public void setAcqusitioncost(BigDecimal acqusitioncost) {
        this.acqusitioncost = acqusitioncost;
    }
    public BigDecimal getPotentiallifetimevalue() {
        return this.potentiallifetimevalue;
    }
    
    public void setPotentiallifetimevalue(BigDecimal potentiallifetimevalue) {
        this.potentiallifetimevalue = potentiallifetimevalue;
    }
    public BigDecimal getActuallifetimevalue() {
        return this.actuallifetimevalue;
    }
    
    public void setActuallifetimevalue(BigDecimal actuallifetimevalue) {
        this.actuallifetimevalue = actuallifetimevalue;
    }
    public Long getShareofcustomer() {
        return this.shareofcustomer;
    }
    
    public void setShareofcustomer(Long shareofcustomer) {
        this.shareofcustomer = shareofcustomer;
    }
    public Character getPaymentrule() {
        return this.paymentrule;
    }
    
    public void setPaymentrule(Character paymentrule) {
        this.paymentrule = paymentrule;
    }
    public BigDecimal getSoCreditlimit() {
        return this.soCreditlimit;
    }
    
    public void setSoCreditlimit(BigDecimal soCreditlimit) {
        this.soCreditlimit = soCreditlimit;
    }
    public BigDecimal getSoCreditused() {
        return this.soCreditused;
    }
    
    public void setSoCreditused(BigDecimal soCreditused) {
        this.soCreditused = soCreditused;
    }
    public Character getIsdiscountprinted() {
        return this.isdiscountprinted;
    }
    
    public void setIsdiscountprinted(Character isdiscountprinted) {
        this.isdiscountprinted = isdiscountprinted;
    }
    public String getSoDescription() {
        return this.soDescription;
    }
    
    public void setSoDescription(String soDescription) {
        this.soDescription = soDescription;
    }
    public String getPoreference() {
        return this.poreference;
    }
    
    public void setPoreference(String poreference) {
        this.poreference = poreference;
    }
    public Character getPaymentrulepo() {
        return this.paymentrulepo;
    }
    
    public void setPaymentrulepo(Character paymentrulepo) {
        this.paymentrulepo = paymentrulepo;
    }
    public Long getDocumentcopies() {
        return this.documentcopies;
    }
    
    public void setDocumentcopies(Long documentcopies) {
        this.documentcopies = documentcopies;
    }
    public Character getInvoicerule() {
        return this.invoicerule;
    }
    
    public void setInvoicerule(Character invoicerule) {
        this.invoicerule = invoicerule;
    }
    public Character getDeliveryrule() {
        return this.deliveryrule;
    }
    
    public void setDeliveryrule(Character deliveryrule) {
        this.deliveryrule = deliveryrule;
    }
    public Character getFreightcostrule() {
        return this.freightcostrule;
    }
    
    public void setFreightcostrule(Character freightcostrule) {
        this.freightcostrule = freightcostrule;
    }
    public Character getDeliveryviarule() {
        return this.deliveryviarule;
    }
    
    public void setDeliveryviarule(Character deliveryviarule) {
        this.deliveryviarule = deliveryviarule;
    }
    public char getSendemail() {
        return this.sendemail;
    }
    
    public void setSendemail(char sendemail) {
        this.sendemail = sendemail;
    }
    public Character getSocreditstatus() {
        return this.socreditstatus;
    }
    
    public void setSocreditstatus(Character socreditstatus) {
        this.socreditstatus = socreditstatus;
    }
    public Long getShelflifeminpct() {
        return this.shelflifeminpct;
    }
    
    public void setShelflifeminpct(Long shelflifeminpct) {
        this.shelflifeminpct = shelflifeminpct;
    }
    public BigDecimal getFlatdiscount() {
        return this.flatdiscount;
    }
    
    public void setFlatdiscount(BigDecimal flatdiscount) {
        this.flatdiscount = flatdiscount;
    }
    public BigDecimal getTotalopenbalance() {
        return this.totalopenbalance;
    }
    
    public void setTotalopenbalance(BigDecimal totalopenbalance) {
        this.totalopenbalance = totalopenbalance;
    }
    public Date getDunninggrace() {
        return this.dunninggrace;
    }
    
    public void setDunninggrace(Date dunninggrace) {
        this.dunninggrace = dunninggrace;
    }
    public char getIspotaxexempt() {
        return this.ispotaxexempt;
    }
    
    public void setIspotaxexempt(char ispotaxexempt) {
        this.ispotaxexempt = ispotaxexempt;
    }
    public Character getIsmanufacturer() {
        return this.ismanufacturer;
    }
    
    public void setIsmanufacturer(Character ismanufacturer) {
        this.ismanufacturer = ismanufacturer;
    }
    public Set getAdUsers() {
        return this.adUsers;
    }
    
    public void setAdUsers(Set adUsers) {
        this.adUsers = adUsers;
    }
    public Set getCBpartnerLocations() {
        return this.CBpartnerLocations;
    }
    
    public void setCBpartnerLocations(Set CBpartnerLocations) {
        this.CBpartnerLocations = CBpartnerLocations;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }
    public Set getAdWfNodes() {
        return this.adWfNodes;
    }
    
    public void setAdWfNodes(Set adWfNodes) {
        this.adWfNodes = adWfNodes;
    }




}


