package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CBpartnerLocation generated by hbm2java
 */
public class CBpartnerLocation  implements java.io.Serializable {


     private long CBpartnerLocationId;
     private CBpartner CBpartner;
     private CSalesregion CSalesregion;
     private AdClient adClient;
     private CLocation CLocation;
     private AdOrg adOrg;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private char isbillto;
     private char isshipto;
     private char ispayfrom;
     private char isremitto;
     private String phone;
     private String phone2;
     private String fax;
     private String isdn;
     private Set adUsers = new HashSet(0);

    public CBpartnerLocation() {
    }

	
    public CBpartnerLocation(long CBpartnerLocationId, CBpartner CBpartner, AdClient adClient, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isbillto, char isshipto, char ispayfrom, char isremitto) {
        this.CBpartnerLocationId = CBpartnerLocationId;
        this.CBpartner = CBpartner;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isbillto = isbillto;
        this.isshipto = isshipto;
        this.ispayfrom = ispayfrom;
        this.isremitto = isremitto;
    }
    public CBpartnerLocation(long CBpartnerLocationId, CBpartner CBpartner, CSalesregion CSalesregion, AdClient adClient, CLocation CLocation, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isbillto, char isshipto, char ispayfrom, char isremitto, String phone, String phone2, String fax, String isdn, Set adUsers) {
       this.CBpartnerLocationId = CBpartnerLocationId;
       this.CBpartner = CBpartner;
       this.CSalesregion = CSalesregion;
       this.adClient = adClient;
       this.CLocation = CLocation;
       this.adOrg = adOrg;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.isbillto = isbillto;
       this.isshipto = isshipto;
       this.ispayfrom = ispayfrom;
       this.isremitto = isremitto;
       this.phone = phone;
       this.phone2 = phone2;
       this.fax = fax;
       this.isdn = isdn;
       this.adUsers = adUsers;
    }
   
    public long getCBpartnerLocationId() {
        return this.CBpartnerLocationId;
    }
    
    public void setCBpartnerLocationId(long CBpartnerLocationId) {
        this.CBpartnerLocationId = CBpartnerLocationId;
    }
    public CBpartner getCBpartner() {
        return this.CBpartner;
    }
    
    public void setCBpartner(CBpartner CBpartner) {
        this.CBpartner = CBpartner;
    }
    public CSalesregion getCSalesregion() {
        return this.CSalesregion;
    }
    
    public void setCSalesregion(CSalesregion CSalesregion) {
        this.CSalesregion = CSalesregion;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CLocation getCLocation() {
        return this.CLocation;
    }
    
    public void setCLocation(CLocation CLocation) {
        this.CLocation = CLocation;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getIsbillto() {
        return this.isbillto;
    }
    
    public void setIsbillto(char isbillto) {
        this.isbillto = isbillto;
    }
    public char getIsshipto() {
        return this.isshipto;
    }
    
    public void setIsshipto(char isshipto) {
        this.isshipto = isshipto;
    }
    public char getIspayfrom() {
        return this.ispayfrom;
    }
    
    public void setIspayfrom(char ispayfrom) {
        this.ispayfrom = ispayfrom;
    }
    public char getIsremitto() {
        return this.isremitto;
    }
    
    public void setIsremitto(char isremitto) {
        this.isremitto = isremitto;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getIsdn() {
        return this.isdn;
    }
    
    public void setIsdn(String isdn) {
        this.isdn = isdn;
    }
    public Set getAdUsers() {
        return this.adUsers;
    }
    
    public void setAdUsers(Set adUsers) {
        this.adUsers = adUsers;
    }




}


