package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CCity generated by hbm2java
 */
public class CCity  implements java.io.Serializable {


     private long CCityId;
     private CRegion CRegion;
     private AdClient adClient;
     private CCountry CCountry;
     private AdOrg adOrg;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String locode;
     private String coordinates;
     private String postal;
     private String areacode;
     private Set CLocations = new HashSet(0);

    public CCity() {
    }

	
    public CCity(long CCityId, AdClient adClient, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name) {
        this.CCityId = CCityId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
    }
    public CCity(long CCityId, CRegion CRegion, AdClient adClient, CCountry CCountry, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String locode, String coordinates, String postal, String areacode, Set CLocations) {
       this.CCityId = CCityId;
       this.CRegion = CRegion;
       this.adClient = adClient;
       this.CCountry = CCountry;
       this.adOrg = adOrg;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.locode = locode;
       this.coordinates = coordinates;
       this.postal = postal;
       this.areacode = areacode;
       this.CLocations = CLocations;
    }
   
    public long getCCityId() {
        return this.CCityId;
    }
    
    public void setCCityId(long CCityId) {
        this.CCityId = CCityId;
    }
    public CRegion getCRegion() {
        return this.CRegion;
    }
    
    public void setCRegion(CRegion CRegion) {
        this.CRegion = CRegion;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CCountry getCCountry() {
        return this.CCountry;
    }
    
    public void setCCountry(CCountry CCountry) {
        this.CCountry = CCountry;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocode() {
        return this.locode;
    }
    
    public void setLocode(String locode) {
        this.locode = locode;
    }
    public String getCoordinates() {
        return this.coordinates;
    }
    
    public void setCoordinates(String coordinates) {
        this.coordinates = coordinates;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public String getAreacode() {
        return this.areacode;
    }
    
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }
    public Set getCLocations() {
        return this.CLocations;
    }
    
    public void setCLocations(Set CLocations) {
        this.CLocations = CLocations;
    }




}


