package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CGreeting generated by hbm2java
 */
public class CGreeting  implements java.io.Serializable {


     private long CGreetingId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String greeting;
     private char isfirstnameonly;
     private char isdefault;
     private Set CBpartners = new HashSet(0);
     private Set adUsers = new HashSet(0);

    public CGreeting() {
    }

	
    public CGreeting(long CGreetingId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isfirstnameonly, char isdefault) {
        this.CGreetingId = CGreetingId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isfirstnameonly = isfirstnameonly;
        this.isdefault = isdefault;
    }
    public CGreeting(long CGreetingId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String greeting, char isfirstnameonly, char isdefault, Set CBpartners, Set adUsers) {
       this.CGreetingId = CGreetingId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.greeting = greeting;
       this.isfirstnameonly = isfirstnameonly;
       this.isdefault = isdefault;
       this.CBpartners = CBpartners;
       this.adUsers = adUsers;
    }
   
    public long getCGreetingId() {
        return this.CGreetingId;
    }
    
    public void setCGreetingId(long CGreetingId) {
        this.CGreetingId = CGreetingId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGreeting() {
        return this.greeting;
    }
    
    public void setGreeting(String greeting) {
        this.greeting = greeting;
    }
    public char getIsfirstnameonly() {
        return this.isfirstnameonly;
    }
    
    public void setIsfirstnameonly(char isfirstnameonly) {
        this.isfirstnameonly = isfirstnameonly;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }
    public Set getAdUsers() {
        return this.adUsers;
    }
    
    public void setAdUsers(Set adUsers) {
        this.adUsers = adUsers;
    }




}


