package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CInvoiceschedule generated by hbm2java
 */
public class CInvoiceschedule  implements java.io.Serializable {


     private long CInvoicescheduleId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private char isamount;
     private BigDecimal amt;
     private char invoicefrequency;
     private Character invoiceweekday;
     private Character invoiceweekdaycutoff;
     private Character eveninvoiceweek;
     private Long invoiceday;
     private Long invoicedaycutoff;
     private char isdefault;
     private Set CBpartners = new HashSet(0);

    public CInvoiceschedule() {
    }

	
    public CInvoiceschedule(long CInvoicescheduleId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isamount, char invoicefrequency, char isdefault) {
        this.CInvoicescheduleId = CInvoicescheduleId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isamount = isamount;
        this.invoicefrequency = invoicefrequency;
        this.isdefault = isdefault;
    }
    public CInvoiceschedule(long CInvoicescheduleId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, char isamount, BigDecimal amt, char invoicefrequency, Character invoiceweekday, Character invoiceweekdaycutoff, Character eveninvoiceweek, Long invoiceday, Long invoicedaycutoff, char isdefault, Set CBpartners) {
       this.CInvoicescheduleId = CInvoicescheduleId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.isamount = isamount;
       this.amt = amt;
       this.invoicefrequency = invoicefrequency;
       this.invoiceweekday = invoiceweekday;
       this.invoiceweekdaycutoff = invoiceweekdaycutoff;
       this.eveninvoiceweek = eveninvoiceweek;
       this.invoiceday = invoiceday;
       this.invoicedaycutoff = invoicedaycutoff;
       this.isdefault = isdefault;
       this.CBpartners = CBpartners;
    }
   
    public long getCInvoicescheduleId() {
        return this.CInvoicescheduleId;
    }
    
    public void setCInvoicescheduleId(long CInvoicescheduleId) {
        this.CInvoicescheduleId = CInvoicescheduleId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getIsamount() {
        return this.isamount;
    }
    
    public void setIsamount(char isamount) {
        this.isamount = isamount;
    }
    public BigDecimal getAmt() {
        return this.amt;
    }
    
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    public char getInvoicefrequency() {
        return this.invoicefrequency;
    }
    
    public void setInvoicefrequency(char invoicefrequency) {
        this.invoicefrequency = invoicefrequency;
    }
    public Character getInvoiceweekday() {
        return this.invoiceweekday;
    }
    
    public void setInvoiceweekday(Character invoiceweekday) {
        this.invoiceweekday = invoiceweekday;
    }
    public Character getInvoiceweekdaycutoff() {
        return this.invoiceweekdaycutoff;
    }
    
    public void setInvoiceweekdaycutoff(Character invoiceweekdaycutoff) {
        this.invoiceweekdaycutoff = invoiceweekdaycutoff;
    }
    public Character getEveninvoiceweek() {
        return this.eveninvoiceweek;
    }
    
    public void setEveninvoiceweek(Character eveninvoiceweek) {
        this.eveninvoiceweek = eveninvoiceweek;
    }
    public Long getInvoiceday() {
        return this.invoiceday;
    }
    
    public void setInvoiceday(Long invoiceday) {
        this.invoiceday = invoiceday;
    }
    public Long getInvoicedaycutoff() {
        return this.invoicedaycutoff;
    }
    
    public void setInvoicedaycutoff(Long invoicedaycutoff) {
        this.invoicedaycutoff = invoicedaycutoff;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Set getCBpartners() {
        return this.CBpartners;
    }
    
    public void setCBpartners(Set CBpartners) {
        this.CBpartners = CBpartners;
    }




}


