package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CJob generated by hbm2java
 */
public class CJob  implements java.io.Serializable {


     private long CJobId;
     private CJobcategory CJobcategory;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String help;
     private char isemployee;
     private Set adUsers = new HashSet(0);

    public CJob() {
    }

	
    public CJob(long CJobId, CJobcategory CJobcategory, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isemployee) {
        this.CJobId = CJobId;
        this.CJobcategory = CJobcategory;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isemployee = isemployee;
    }
    public CJob(long CJobId, CJobcategory CJobcategory, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String help, char isemployee, Set adUsers) {
       this.CJobId = CJobId;
       this.CJobcategory = CJobcategory;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.help = help;
       this.isemployee = isemployee;
       this.adUsers = adUsers;
    }
   
    public long getCJobId() {
        return this.CJobId;
    }
    
    public void setCJobId(long CJobId) {
        this.CJobId = CJobId;
    }
    public CJobcategory getCJobcategory() {
        return this.CJobcategory;
    }
    
    public void setCJobcategory(CJobcategory CJobcategory) {
        this.CJobcategory = CJobcategory;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public char getIsemployee() {
        return this.isemployee;
    }
    
    public void setIsemployee(char isemployee) {
        this.isemployee = isemployee;
    }
    public Set getAdUsers() {
        return this.adUsers;
    }
    
    public void setAdUsers(Set adUsers) {
        this.adUsers = adUsers;
    }




}


