package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CLocation generated by hbm2java
 */
public class CLocation  implements java.io.Serializable {


     private long CLocationId;
     private CRegion CRegion;
     private AdClient adClient;
     private CCountry CCountry;
     private AdOrg adOrg;
     private CCity CCity;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String address1;
     private String address2;
     private String city;
     private String postal;
     private String postalAdd;
     private String regionname;
     private String address3;
     private String address4;
     private Set CBpartnerLocations = new HashSet(0);
     private Set MWarehouses = new HashSet(0);

    public CLocation() {
    }

	
    public CLocation(long CLocationId, AdClient adClient, CCountry CCountry, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby) {
        this.CLocationId = CLocationId;
        this.adClient = adClient;
        this.CCountry = CCountry;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
    }
    public CLocation(long CLocationId, CRegion CRegion, AdClient adClient, CCountry CCountry, AdOrg adOrg, CCity CCity, char isactive, Date created, long createdby, Date updated, long updatedby, String address1, String address2, String city, String postal, String postalAdd, String regionname, String address3, String address4, Set CBpartnerLocations, Set MWarehouses) {
       this.CLocationId = CLocationId;
       this.CRegion = CRegion;
       this.adClient = adClient;
       this.CCountry = CCountry;
       this.adOrg = adOrg;
       this.CCity = CCity;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.postal = postal;
       this.postalAdd = postalAdd;
       this.regionname = regionname;
       this.address3 = address3;
       this.address4 = address4;
       this.CBpartnerLocations = CBpartnerLocations;
       this.MWarehouses = MWarehouses;
    }
   
    public long getCLocationId() {
        return this.CLocationId;
    }
    
    public void setCLocationId(long CLocationId) {
        this.CLocationId = CLocationId;
    }
    public CRegion getCRegion() {
        return this.CRegion;
    }
    
    public void setCRegion(CRegion CRegion) {
        this.CRegion = CRegion;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CCountry getCCountry() {
        return this.CCountry;
    }
    
    public void setCCountry(CCountry CCountry) {
        this.CCountry = CCountry;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public CCity getCCity() {
        return this.CCity;
    }
    
    public void setCCity(CCity CCity) {
        this.CCity = CCity;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public String getPostalAdd() {
        return this.postalAdd;
    }
    
    public void setPostalAdd(String postalAdd) {
        this.postalAdd = postalAdd;
    }
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }
    public Set getCBpartnerLocations() {
        return this.CBpartnerLocations;
    }
    
    public void setCBpartnerLocations(Set CBpartnerLocations) {
        this.CBpartnerLocations = CBpartnerLocations;
    }
    public Set getMWarehouses() {
        return this.MWarehouses;
    }
    
    public void setMWarehouses(Set MWarehouses) {
        this.MWarehouses = MWarehouses;
    }




}


