package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CMenuetl generated by hbm2java
 */
public class CMenuetl  implements java.io.Serializable {


     private long CMenuetlId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String description;
     private String url;
     private long level;
     private String image;
     private long submenu;
     private long width;

    public CMenuetl() {
    }

    public CMenuetl(long CMenuetlId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String description, String url, long level, String image, long submenu, long width) {
       this.CMenuetlId = CMenuetlId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.description = description;
       this.url = url;
       this.level = level;
       this.image = image;
       this.submenu = submenu;
       this.width = width;
    }
   
    public long getCMenuetlId() {
        return this.CMenuetlId;
    }
    
    public void setCMenuetlId(long CMenuetlId) {
        this.CMenuetlId = CMenuetlId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public long getLevel() {
        return this.level;
    }
    
    public void setLevel(long level) {
        this.level = level;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public long getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(long submenu) {
        this.submenu = submenu;
    }
    public long getWidth() {
        return this.width;
    }
    
    public void setWidth(long width) {
        this.width = width;
    }




}


