package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CPaymentterm generated by hbm2java
 */
public class CPaymentterm  implements java.io.Serializable {


     private long CPaymenttermId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String documentnote;
     private char afterdelivery;
     private char isduefixed;
     private long netdays;
     private long gracedays;
     private Long fixmonthcutoff;
     private Long fixmonthday;
     private Long fixmonthoffset;
     private long discountdays;
     private BigDecimal discount;
     private long discountdays2;
     private BigDecimal discount2;
     private Character isnextbusinessday;
     private Character isdefault;
     private String value;
     private Character netday;
     private char isvalid;
     private Character processing;
     private Set CBpartnersForCPaymenttermId = new HashSet(0);
     private Set CBpartnersForPoPaymenttermId = new HashSet(0);

    public CPaymentterm() {
    }

	
    public CPaymentterm(long CPaymenttermId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char afterdelivery, char isduefixed, long netdays, long gracedays, long discountdays, BigDecimal discount, long discountdays2, BigDecimal discount2, String value, char isvalid) {
        this.CPaymenttermId = CPaymenttermId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.afterdelivery = afterdelivery;
        this.isduefixed = isduefixed;
        this.netdays = netdays;
        this.gracedays = gracedays;
        this.discountdays = discountdays;
        this.discount = discount;
        this.discountdays2 = discountdays2;
        this.discount2 = discount2;
        this.value = value;
        this.isvalid = isvalid;
    }
    public CPaymentterm(long CPaymenttermId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String documentnote, char afterdelivery, char isduefixed, long netdays, long gracedays, Long fixmonthcutoff, Long fixmonthday, Long fixmonthoffset, long discountdays, BigDecimal discount, long discountdays2, BigDecimal discount2, Character isnextbusinessday, Character isdefault, String value, Character netday, char isvalid, Character processing, Set CBpartnersForCPaymenttermId, Set CBpartnersForPoPaymenttermId) {
       this.CPaymenttermId = CPaymenttermId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.documentnote = documentnote;
       this.afterdelivery = afterdelivery;
       this.isduefixed = isduefixed;
       this.netdays = netdays;
       this.gracedays = gracedays;
       this.fixmonthcutoff = fixmonthcutoff;
       this.fixmonthday = fixmonthday;
       this.fixmonthoffset = fixmonthoffset;
       this.discountdays = discountdays;
       this.discount = discount;
       this.discountdays2 = discountdays2;
       this.discount2 = discount2;
       this.isnextbusinessday = isnextbusinessday;
       this.isdefault = isdefault;
       this.value = value;
       this.netday = netday;
       this.isvalid = isvalid;
       this.processing = processing;
       this.CBpartnersForCPaymenttermId = CBpartnersForCPaymenttermId;
       this.CBpartnersForPoPaymenttermId = CBpartnersForPoPaymenttermId;
    }
   
    public long getCPaymenttermId() {
        return this.CPaymenttermId;
    }
    
    public void setCPaymenttermId(long CPaymenttermId) {
        this.CPaymenttermId = CPaymenttermId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDocumentnote() {
        return this.documentnote;
    }
    
    public void setDocumentnote(String documentnote) {
        this.documentnote = documentnote;
    }
    public char getAfterdelivery() {
        return this.afterdelivery;
    }
    
    public void setAfterdelivery(char afterdelivery) {
        this.afterdelivery = afterdelivery;
    }
    public char getIsduefixed() {
        return this.isduefixed;
    }
    
    public void setIsduefixed(char isduefixed) {
        this.isduefixed = isduefixed;
    }
    public long getNetdays() {
        return this.netdays;
    }
    
    public void setNetdays(long netdays) {
        this.netdays = netdays;
    }
    public long getGracedays() {
        return this.gracedays;
    }
    
    public void setGracedays(long gracedays) {
        this.gracedays = gracedays;
    }
    public Long getFixmonthcutoff() {
        return this.fixmonthcutoff;
    }
    
    public void setFixmonthcutoff(Long fixmonthcutoff) {
        this.fixmonthcutoff = fixmonthcutoff;
    }
    public Long getFixmonthday() {
        return this.fixmonthday;
    }
    
    public void setFixmonthday(Long fixmonthday) {
        this.fixmonthday = fixmonthday;
    }
    public Long getFixmonthoffset() {
        return this.fixmonthoffset;
    }
    
    public void setFixmonthoffset(Long fixmonthoffset) {
        this.fixmonthoffset = fixmonthoffset;
    }
    public long getDiscountdays() {
        return this.discountdays;
    }
    
    public void setDiscountdays(long discountdays) {
        this.discountdays = discountdays;
    }
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
    public long getDiscountdays2() {
        return this.discountdays2;
    }
    
    public void setDiscountdays2(long discountdays2) {
        this.discountdays2 = discountdays2;
    }
    public BigDecimal getDiscount2() {
        return this.discount2;
    }
    
    public void setDiscount2(BigDecimal discount2) {
        this.discount2 = discount2;
    }
    public Character getIsnextbusinessday() {
        return this.isnextbusinessday;
    }
    
    public void setIsnextbusinessday(Character isnextbusinessday) {
        this.isnextbusinessday = isnextbusinessday;
    }
    public Character getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(Character isdefault) {
        this.isdefault = isdefault;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Character getNetday() {
        return this.netday;
    }
    
    public void setNetday(Character netday) {
        this.netday = netday;
    }
    public char getIsvalid() {
        return this.isvalid;
    }
    
    public void setIsvalid(char isvalid) {
        this.isvalid = isvalid;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public Set getCBpartnersForCPaymenttermId() {
        return this.CBpartnersForCPaymenttermId;
    }
    
    public void setCBpartnersForCPaymenttermId(Set CBpartnersForCPaymenttermId) {
        this.CBpartnersForCPaymenttermId = CBpartnersForCPaymenttermId;
    }
    public Set getCBpartnersForPoPaymenttermId() {
        return this.CBpartnersForPoPaymenttermId;
    }
    
    public void setCBpartnersForPoPaymenttermId(Set CBpartnersForPoPaymenttermId) {
        this.CBpartnersForPoPaymenttermId = CBpartnersForPoPaymenttermId;
    }




}


