package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CRegion generated by hbm2java
 */
public class CRegion  implements java.io.Serializable {


     private long CRegionId;
     private AdClient adClient;
     private CCountry CCountry;
     private AdOrg adOrg;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private Character isdefault;
     private Set CCities = new HashSet(0);
     private Set CLocations = new HashSet(0);

    public CRegion() {
    }

	
    public CRegion(long CRegionId, AdClient adClient, CCountry CCountry, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name) {
        this.CRegionId = CRegionId;
        this.adClient = adClient;
        this.CCountry = CCountry;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
    }
    public CRegion(long CRegionId, AdClient adClient, CCountry CCountry, AdOrg adOrg, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, Character isdefault, Set CCities, Set CLocations) {
       this.CRegionId = CRegionId;
       this.adClient = adClient;
       this.CCountry = CCountry;
       this.adOrg = adOrg;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.isdefault = isdefault;
       this.CCities = CCities;
       this.CLocations = CLocations;
    }
   
    public long getCRegionId() {
        return this.CRegionId;
    }
    
    public void setCRegionId(long CRegionId) {
        this.CRegionId = CRegionId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public CCountry getCCountry() {
        return this.CCountry;
    }
    
    public void setCCountry(CCountry CCountry) {
        this.CCountry = CCountry;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Character getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(Character isdefault) {
        this.isdefault = isdefault;
    }
    public Set getCCities() {
        return this.CCities;
    }
    
    public void setCCities(Set CCities) {
        this.CCities = CCities;
    }
    public Set getCLocations() {
        return this.CLocations;
    }
    
    public void setCLocations(Set CLocations) {
        this.CLocations = CLocations;
    }




}


