package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CSalesregion generated by hbm2java
 */
public class CSalesregion  implements java.io.Serializable {


     private long CSalesregionId;
     private AdUser adUser;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String value;
     private String name;
     private String description;
     private char issummary;
     private char isdefault;
     private Set CBpartnerLocations = new HashSet(0);

    public CSalesregion() {
    }

	
    public CSalesregion(long CSalesregionId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name, char issummary, char isdefault) {
        this.CSalesregionId = CSalesregionId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.value = value;
        this.name = name;
        this.issummary = issummary;
        this.isdefault = isdefault;
    }
    public CSalesregion(long CSalesregionId, AdUser adUser, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name, String description, char issummary, char isdefault, Set CBpartnerLocations) {
       this.CSalesregionId = CSalesregionId;
       this.adUser = adUser;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.value = value;
       this.name = name;
       this.description = description;
       this.issummary = issummary;
       this.isdefault = isdefault;
       this.CBpartnerLocations = CBpartnerLocations;
    }
   
    public long getCSalesregionId() {
        return this.CSalesregionId;
    }
    
    public void setCSalesregionId(long CSalesregionId) {
        this.CSalesregionId = CSalesregionId;
    }
    public AdUser getAdUser() {
        return this.adUser;
    }
    
    public void setAdUser(AdUser adUser) {
        this.adUser = adUser;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getIssummary() {
        return this.issummary;
    }
    
    public void setIssummary(char issummary) {
        this.issummary = issummary;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Set getCBpartnerLocations() {
        return this.CBpartnerLocations;
    }
    
    public void setCBpartnerLocations(Set CBpartnerLocations) {
        this.CBpartnerLocations = CBpartnerLocations;
    }




}


