package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CTaxcategory generated by hbm2java
 */
public class CTaxcategory  implements java.io.Serializable {


     private long CTaxcategoryId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private String commoditycode;
     private char isdefault;
     private Set SResourcetypes = new HashSet(0);

    public CTaxcategory() {
    }

	
    public CTaxcategory(long CTaxcategoryId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, char isdefault) {
        this.CTaxcategoryId = CTaxcategoryId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.isdefault = isdefault;
    }
    public CTaxcategory(long CTaxcategoryId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, String commoditycode, char isdefault, Set SResourcetypes) {
       this.CTaxcategoryId = CTaxcategoryId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.commoditycode = commoditycode;
       this.isdefault = isdefault;
       this.SResourcetypes = SResourcetypes;
    }
   
    public long getCTaxcategoryId() {
        return this.CTaxcategoryId;
    }
    
    public void setCTaxcategoryId(long CTaxcategoryId) {
        this.CTaxcategoryId = CTaxcategoryId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCommoditycode() {
        return this.commoditycode;
    }
    
    public void setCommoditycode(String commoditycode) {
        this.commoditycode = commoditycode;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public Set getSResourcetypes() {
        return this.SResourcetypes;
    }
    
    public void setSResourcetypes(Set SResourcetypes) {
        this.SResourcetypes = SResourcetypes;
    }




}


