package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CUom generated by hbm2java
 */
public class CUom  implements java.io.Serializable {


     private long CUomId;
     private AdClient adClient;
     private AdOrg adOrg;
     private char isactive;
     private Date created;
     private Date updated;
     private long createdby;
     private long updatedby;
     private String x12de355;
     private String uomsymbol;
     private String name;
     private String description;
     private long stdprecision;
     private long costingprecision;
     private char isdefault;
     private String uomtype;
     private Set SResourcetypes = new HashSet(0);

    public CUom() {
    }

	
    public CUom(long CUomId, AdClient adClient, AdOrg adOrg, char isactive, Date created, Date updated, long createdby, long updatedby, String x12de355, String name, long stdprecision, long costingprecision, char isdefault) {
        this.CUomId = CUomId;
        this.adClient = adClient;
        this.adOrg = adOrg;
        this.isactive = isactive;
        this.created = created;
        this.updated = updated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.x12de355 = x12de355;
        this.name = name;
        this.stdprecision = stdprecision;
        this.costingprecision = costingprecision;
        this.isdefault = isdefault;
    }
    public CUom(long CUomId, AdClient adClient, AdOrg adOrg, char isactive, Date created, Date updated, long createdby, long updatedby, String x12de355, String uomsymbol, String name, String description, long stdprecision, long costingprecision, char isdefault, String uomtype, Set SResourcetypes) {
       this.CUomId = CUomId;
       this.adClient = adClient;
       this.adOrg = adOrg;
       this.isactive = isactive;
       this.created = created;
       this.updated = updated;
       this.createdby = createdby;
       this.updatedby = updatedby;
       this.x12de355 = x12de355;
       this.uomsymbol = uomsymbol;
       this.name = name;
       this.description = description;
       this.stdprecision = stdprecision;
       this.costingprecision = costingprecision;
       this.isdefault = isdefault;
       this.uomtype = uomtype;
       this.SResourcetypes = SResourcetypes;
    }
   
    public long getCUomId() {
        return this.CUomId;
    }
    
    public void setCUomId(long CUomId) {
        this.CUomId = CUomId;
    }
    public AdClient getAdClient() {
        return this.adClient;
    }
    
    public void setAdClient(AdClient adClient) {
        this.adClient = adClient;
    }
    public AdOrg getAdOrg() {
        return this.adOrg;
    }
    
    public void setAdOrg(AdOrg adOrg) {
        this.adOrg = adOrg;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getX12de355() {
        return this.x12de355;
    }
    
    public void setX12de355(String x12de355) {
        this.x12de355 = x12de355;
    }
    public String getUomsymbol() {
        return this.uomsymbol;
    }
    
    public void setUomsymbol(String uomsymbol) {
        this.uomsymbol = uomsymbol;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getStdprecision() {
        return this.stdprecision;
    }
    
    public void setStdprecision(long stdprecision) {
        this.stdprecision = stdprecision;
    }
    public long getCostingprecision() {
        return this.costingprecision;
    }
    
    public void setCostingprecision(long costingprecision) {
        this.costingprecision = costingprecision;
    }
    public char getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(char isdefault) {
        this.isdefault = isdefault;
    }
    public String getUomtype() {
        return this.uomtype;
    }
    
    public void setUomtype(String uomtype) {
        this.uomtype = uomtype;
    }
    public Set getSResourcetypes() {
        return this.SResourcetypes;
    }
    
    public void setSResourcetypes(Set SResourcetypes) {
        this.SResourcetypes = SResourcetypes;
    }




}


