package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpProcessor generated by hbm2java
 */
public class ExpProcessor  implements java.io.Serializable {


     private long expProcessorId;
     private ExpProcessorType expProcessorType;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String value;
     private String name;
     private String description;
     private String help;
     private String host;
     private Long port;
     private String account;
     private String passwordinfo;
     private Set adReplicationstrategies = new HashSet(0);

    public ExpProcessor() {
    }

	
    public ExpProcessor(long expProcessorId, ExpProcessorType expProcessorType, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name) {
        this.expProcessorId = expProcessorId;
        this.expProcessorType = expProcessorType;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.value = value;
        this.name = name;
    }
    public ExpProcessor(long expProcessorId, ExpProcessorType expProcessorType, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String value, String name, String description, String help, String host, Long port, String account, String passwordinfo, Set adReplicationstrategies) {
       this.expProcessorId = expProcessorId;
       this.expProcessorType = expProcessorType;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.value = value;
       this.name = name;
       this.description = description;
       this.help = help;
       this.host = host;
       this.port = port;
       this.account = account;
       this.passwordinfo = passwordinfo;
       this.adReplicationstrategies = adReplicationstrategies;
    }
   
    public long getExpProcessorId() {
        return this.expProcessorId;
    }
    
    public void setExpProcessorId(long expProcessorId) {
        this.expProcessorId = expProcessorId;
    }
    public ExpProcessorType getExpProcessorType() {
        return this.expProcessorType;
    }
    
    public void setExpProcessorType(ExpProcessorType expProcessorType) {
        this.expProcessorType = expProcessorType;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getHelp() {
        return this.help;
    }
    
    public void setHelp(String help) {
        this.help = help;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public Long getPort() {
        return this.port;
    }
    
    public void setPort(Long port) {
        this.port = port;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getPasswordinfo() {
        return this.passwordinfo;
    }
    
    public void setPasswordinfo(String passwordinfo) {
        this.passwordinfo = passwordinfo;
    }
    public Set getAdReplicationstrategies() {
        return this.adReplicationstrategies;
    }
    
    public void setAdReplicationstrategies(Set adReplicationstrategies) {
        this.adReplicationstrategies = adReplicationstrategies;
    }




}


