package com.mx.nibble.domain;
// Generated Dec 19, 2014 6:33:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MDiscountschema generated by hbm2java
 */
public class MDiscountschema  implements java.io.Serializable {


     private long MDiscountschemaId;
     private long adClientId;
     private long adOrgId;
     private char isactive;
     private Date created;
     private long createdby;
     private Date updated;
     private long updatedby;
     private String name;
     private String description;
     private Date validfrom;
     private char discounttype;
     private String script;
     private BigDecimal flatdiscount;
     private char isquantitybased;
     private Character cumulativelevel;
     private Character processing;
     private char isbpartnerflatdiscount;
     private Set CBpGroupsForMDiscountschemaId = new HashSet(0);
     private Set CBpGroupsForPoDiscountschemaId = new HashSet(0);
     private Set CBpartnersForPoDiscountschemaId = new HashSet(0);
     private Set CBpartnersForMDiscountschemaId = new HashSet(0);

    public MDiscountschema() {
    }

	
    public MDiscountschema(long MDiscountschemaId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, Date validfrom, char discounttype, char isquantitybased, char isbpartnerflatdiscount) {
        this.MDiscountschemaId = MDiscountschemaId;
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.validfrom = validfrom;
        this.discounttype = discounttype;
        this.isquantitybased = isquantitybased;
        this.isbpartnerflatdiscount = isbpartnerflatdiscount;
    }
    public MDiscountschema(long MDiscountschemaId, long adClientId, long adOrgId, char isactive, Date created, long createdby, Date updated, long updatedby, String name, String description, Date validfrom, char discounttype, String script, BigDecimal flatdiscount, char isquantitybased, Character cumulativelevel, Character processing, char isbpartnerflatdiscount, Set CBpGroupsForMDiscountschemaId, Set CBpGroupsForPoDiscountschemaId, Set CBpartnersForPoDiscountschemaId, Set CBpartnersForMDiscountschemaId) {
       this.MDiscountschemaId = MDiscountschemaId;
       this.adClientId = adClientId;
       this.adOrgId = adOrgId;
       this.isactive = isactive;
       this.created = created;
       this.createdby = createdby;
       this.updated = updated;
       this.updatedby = updatedby;
       this.name = name;
       this.description = description;
       this.validfrom = validfrom;
       this.discounttype = discounttype;
       this.script = script;
       this.flatdiscount = flatdiscount;
       this.isquantitybased = isquantitybased;
       this.cumulativelevel = cumulativelevel;
       this.processing = processing;
       this.isbpartnerflatdiscount = isbpartnerflatdiscount;
       this.CBpGroupsForMDiscountschemaId = CBpGroupsForMDiscountschemaId;
       this.CBpGroupsForPoDiscountschemaId = CBpGroupsForPoDiscountschemaId;
       this.CBpartnersForPoDiscountschemaId = CBpartnersForPoDiscountschemaId;
       this.CBpartnersForMDiscountschemaId = CBpartnersForMDiscountschemaId;
    }
   
    public long getMDiscountschemaId() {
        return this.MDiscountschemaId;
    }
    
    public void setMDiscountschemaId(long MDiscountschemaId) {
        this.MDiscountschemaId = MDiscountschemaId;
    }
    public long getAdClientId() {
        return this.adClientId;
    }
    
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }
    public long getAdOrgId() {
        return this.adOrgId;
    }
    
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }
    public char getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(char isactive) {
        this.isactive = isactive;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public long getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public long getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }
    public char getDiscounttype() {
        return this.discounttype;
    }
    
    public void setDiscounttype(char discounttype) {
        this.discounttype = discounttype;
    }
    public String getScript() {
        return this.script;
    }
    
    public void setScript(String script) {
        this.script = script;
    }
    public BigDecimal getFlatdiscount() {
        return this.flatdiscount;
    }
    
    public void setFlatdiscount(BigDecimal flatdiscount) {
        this.flatdiscount = flatdiscount;
    }
    public char getIsquantitybased() {
        return this.isquantitybased;
    }
    
    public void setIsquantitybased(char isquantitybased) {
        this.isquantitybased = isquantitybased;
    }
    public Character getCumulativelevel() {
        return this.cumulativelevel;
    }
    
    public void setCumulativelevel(Character cumulativelevel) {
        this.cumulativelevel = cumulativelevel;
    }
    public Character getProcessing() {
        return this.processing;
    }
    
    public void setProcessing(Character processing) {
        this.processing = processing;
    }
    public char getIsbpartnerflatdiscount() {
        return this.isbpartnerflatdiscount;
    }
    
    public void setIsbpartnerflatdiscount(char isbpartnerflatdiscount) {
        this.isbpartnerflatdiscount = isbpartnerflatdiscount;
    }
    public Set getCBpGroupsForMDiscountschemaId() {
        return this.CBpGroupsForMDiscountschemaId;
    }
    
    public void setCBpGroupsForMDiscountschemaId(Set CBpGroupsForMDiscountschemaId) {
        this.CBpGroupsForMDiscountschemaId = CBpGroupsForMDiscountschemaId;
    }
    public Set getCBpGroupsForPoDiscountschemaId() {
        return this.CBpGroupsForPoDiscountschemaId;
    }
    
    public void setCBpGroupsForPoDiscountschemaId(Set CBpGroupsForPoDiscountschemaId) {
        this.CBpGroupsForPoDiscountschemaId = CBpGroupsForPoDiscountschemaId;
    }
    public Set getCBpartnersForPoDiscountschemaId() {
        return this.CBpartnersForPoDiscountschemaId;
    }
    
    public void setCBpartnersForPoDiscountschemaId(Set CBpartnersForPoDiscountschemaId) {
        this.CBpartnersForPoDiscountschemaId = CBpartnersForPoDiscountschemaId;
    }
    public Set getCBpartnersForMDiscountschemaId() {
        return this.CBpartnersForMDiscountschemaId;
    }
    
    public void setCBpartnersForMDiscountschemaId(Set CBpartnersForMDiscountschemaId) {
        this.CBpartnersForMDiscountschemaId = CBpartnersForMDiscountschemaId;
    }




}


